package com.guitarcenter.entities;

import org.springframework.data.annotation.Id;
import org.springframework.data.cassandra.core.mapping.Table;

@Table(value ="container_details")
public class ContainerDetails {
	
@Id	
private String CONTAINER_DETAILS_KEY;
private String ACTUAL_CARRIER_CODE_WHILE_SHIPPING;
private String ACTUAL_DELIVERY_DATE;
private double ACTUAL_FREIGHT_CHARGE;
private String ACTUAL_SHIPMENT_DATE;
private String ALLOCATION_RULE_ID;
private String AUTO_CANCEL_DATE;
private String BUNDLE_FULFILLMENT_MODE;
private String BUNDLE_PARENT_ORDER_LINE_KEY;
private String BUYER_ORGANIZATION_CODE;
private String CANNOT_COMPLETE_AFTER_DATE;
private String CANNOT_COMPLETE_BEFORE_DATE;
private String CARRIER_PICKUP_TIME;
private String CHAINED_FROM_ORDER_HEADER_KEY;
private String CHAINED_FROM_ORDER_LINE_KEY;
private String CHAIN_TYPE;
private String CM_ITEM_CONDITION_MESSAGE;
private String CM_PROMISE_DATE;
private String CM_PROMISE_MESSAGE;
private long COMMITTED_QUANTITY;
private String CONDITION_VARIABLE_1;
private String CONDITION_VARIABLE_2;
private String CONTAINER_CUSTOM_STATUS;
private double CONTAINER_GROSS_WEIGHT;
private String CONTAINER_GROSS_WEIGHT_UOM;
private String CONTAINER_MULTIBOX_DESC;
private String CONTAINER_MULTI_BOX_ID;
private String CONTAINER_NO;
private String CONTAINER_SHIP_DATE;
private String CONTAINER_STATUS_DATE;
private String CREATEPROGID_CONTAINER_DETAILS;
private String CREATEPROGID_ORDER;
private String CREATEPROGID_ORDER_LINE;
private String CREATEPROGID_SHIPMENT;
private String CREATEPROGID_SHIPMENT_CONTAINER;
private String CREATEPROGID_SHIPMENT_LINE;
private String CREATETS_CONTAINER_DETAILS;
private String CREATETS_ORDER;
private String CREATETS_ORDER_LINE;
private String CREATETS_SHIPMENT;
private String CREATETS_SHIPMENT_CONTAINER;
private String CREATETS_SHIPMENT_LINE;
private String CREATEUSERID_CONTAINER_DETAILS;
private String CREATEUSERID_ORDER;
private String CREATEUSERID_ORDER_LINE;
private String CREATEUSERID_SHIPMENT;
private String CREATEUSERID_SHIPMENT_CONTAINER;
private String CREATEUSERID_SHIPMENT_LINE;
private String CUSTOMER_ZIP_CODE;
private String CUSTOM_BACKORDER_EMAIL_SENT_FLAG;
private String CUSTOM_CURRENCY_CONVERSION_RATE;
private String CUSTOM_IS_PO_RESERVED;
private String CUSTOM_IS_PRICING_STRATEGY_COMP;
private String CUSTOM_LINE_SERIAL_NUMBER;
private String CUSTOM_NON_HJ_LINE;
private String DELIVERY_METHOD;
private String DEPENDENT_ON_LINE_KEY;
private String DERIVED_FROM_ORDER_HEADER_KEY;
private String DERIVED_FROM_ORDER_LINE_KEY;
private String DERIVED_FROM_ORDER_RELEASE_KEY;
private String DISPLAY_FOREIGN_CURRENCY;
private String DISPOSITION_CODE;
private String DOCUMENT_TYPE;
private String DRAFT_ORDER_FLAG;
private String EARLIEST_DELIVERY_DATE;
private String EARLIEST_SHIP_DATE;
private String EMPLOYEE_ORDER;
private String ENTERPRISE_CODE;
private String ENTRY_TYPE;
private double ESTIMATED_PRICE;
private String EXCHANGE_TYPE;
private String EXPECTED_DELIVERY_DATE;
private String EXPECTED_SHIPMENT_DATE;
private long FILL_QUANTITY;
private String FREE_GIFT_ITEM_FLAG;
private String FROM_CITY;
private String FROM_STATE;
private String GCSS_STUDENT_ID;
private String GIFT_ORDER;
private String GLOBAL_MSN;
private String HAS_DERIVED_CHILD;
private String HAS_DERIVED_PARENT;
private String INTENTIONAL_BACKORDER;
private String INTL_ORDER_DUTY;
private String INTL_ORDER_HANDLING;
private String INTL_ORDER_VAT;
private String INTL_WEB_ORDER_NO;
private String INT_ORDER_GRAND_TOTAL;
private String INT_ORDER_SHIPPING;
private String INVC_UPDATED_DATE;
private double INVOICED_EXTENDED_PRICE;
private double INVOICED_LINE_TOTAL;
private String IS_COST_OVERRIDDEN;
private String IS_FIRM_PREDEFINED_NODE;
private String IS_FORCED_SOURCED_LINE;
private String IS_NEWLY_ADDED_LINE;
private String IS_STORE_CLEARANCE;
private String IS_WARRANTY_FLAG;
private String ITEM_GROUP_CODE;
private String ITEM_ID;
private String KIT_CODE;
private String LINE_CARRIER_SERVICE_CODE;
private String LINE_FTC_EXCEMPT_FLAG;
private String LINE_FULFILLED_NODE;
private String LINE_FULFILLMENT_TYPE;
private String LINE_GIFT_MESSAGE;
private String LINE_GIFT_WRAP;
private String LINE_HAS_BACKORDERED;
private double LINE_INVENTORY_COST;
private long LINE_INVOICED_PRICED_QTY;
private String LINE_INVOICE_COMPLETE_FLAG;
private String LINE_IS_AMOUNT_COLLECTED;
private String LINE_IS_STORE_FULFILLED;
private double LINE_ITEM_WEIGHT;
private String LINE_ITEM_WEIGHT_UOM;
private long LINE_KIT_QTY;
private double LINE_LIST_PRICE;
private String LINE_LOS;
private String LINE_NODE_AT_ORIGIN;
private long LINE_ORIGINAL_ORDERED_QTY;
private long LINE_OTHER_CHARGES;
private String LINE_PIPE_LINE_KEY;
private String LINE_POS_70_TICKET_NO;
private String LINE_POS_SALES_TICKET_NO;
private String LINE_POS_SKU_NUMBER;
private long LINE_PRICING_QUANTITY;
private String LINE_PROCURE_NODE;
private long LINE_QTY_CANCELLED_IN_SPLIT;
private long LINE_RECEIVED_QTY;
private String LINE_RECEIVING_NODE;
private String LINE_REQUESTED_DELIVERY_DATE;
private String LINE_REQUESTED_SHIP_DATE;
private String LINE_REQ_CANCEL_DATE;
private long LINE_RESCHEDULE_REQ_COUNT;
private long LINE_RETAIL_PRICE;
private String LINE_SCHEDULE_FAILURE_CODE;
private String LINE_SERIAL_NO;
private long LINE_SHIPPED_QUANTITY;
private String LINE_SHIP_ALONE_FLAG;
private String LINE_TAXABLE_FLAG;
private double LINE_TAX_AMOUNT;
private double LINE_TOTAL;
private String MIN_SHIP_BY_DATE;
private String MODIFYPROGID_CONTAINER_DETAILS;
private String MODIFYTPROGID_ORDER;
private String MODIFYTPROGID_ORDER_LINE;
private String MODIFYTPROGID_SHIPMENT;
private String MODIFYTPROGID_SHIPMENT_CONTAINER;
private String MODIFYTPROGID_SHIPMENT_LINE;
private String MODIFYTS_CONTAINER_DETAILS;
private String MODIFYTS_ORDER;
private String MODIFYTS_ORDER_LINE;
private String MODIFYTS_SHIPMENT;
private String MODIFYTS_SHIPMENT_CONTAINER;
private String MODIFYTS_SHIPMENT_LINE;
private String MODIFYUSERID_CONTAINER_DETAILS;
private String MODIFYUSERID_ORDER;
private String MODIFYUSERID_ORDER_LINE;
private String MODIFYUSERID_SHIPMENT;
private String MODIFYUSERID_SHIPMENT_CONTAINER;
private String MODIFYUSERID_SHIPMENT_LINE;
private String NOTIFICATION_REFERENCE;
private String NOTIFICATION_TYPE;
private String OMS_CUSTOMER_ID;
private String ORDERED_STORE_ID;
private String ORDERING_STORE;
private String ORDER_CAPTURE_CHANNEL;
private String ORDER_CLOSED;
private String ORDER_CUSTOM_PO_NOS;
private String ORDER_DATE;
private String ORDER_EXPEDITE_FLAG;
private String ORDER_FTC_EXEMPT;
private String ORDER_HEADER_KEY;
private String ORDER_HOLD_FLAG;
private String ORDER_INVOICE_COMPLETE;
private long ORDER_LINE_INVOICED_QUANTITY;
private String ORDER_LINE_KEY;
private long ORDER_LINE_ORDERED_QTY;
private String ORDER_LINE_TYPE;
private String ORDER_LOS;
private String ORDER_NEXT_ALERT_TS;
private String ORDER_NO;
private long ORDER_ORIGINAL_TAX;
private double ORDER_ORIGINAL_TOTAL_AMOUNT;
private long ORDER_OTHER_CHARGES;
private String ORDER_PICKUP_STORE_ID;
private String ORDER_PURPOSE;
private String ORDER_QUOTE_EXP_DATE;
private String ORDER_RELEASE_KEY;
private String ORDER_REQ_CANCEL_DATE;
private String ORDER_REQ_DELIVERY_DATE;
private String ORDER_REQ_SHIP_DATE;
private long ORDER_TAX;
private String ORDER_TAX_EXEMPT_FLAG;
private double ORDER_TOTAL_AMOUNT;
private String ORDER_TYPE;
private long OVERRIDED_PRICE;
private String PARENT_SHIPMENT_LINE_KEY;
private String PAYMENT_RULE_ID;
private String PAYMENT_STATUS;
private String PICKED_UP_BY;
private long PICKED_UP_BY_CUSTOMER_QTY;
private String PICKED_UP_DATE;
private String PICKED_UP_ID_EXPIRY_DATE;
private String PICKED_UP_ID_TYPE_STATE_ISSUED;
private String PICKED_UP_VERIFICATION_ID;
private String PICKED_UP_VERIFIED;
private String POS_RETURN_11_TICKET_NO;
private String PRICE_OVERRIDE_EMP_ID;
private String PRIORITY_CODE;
private String PROBLEM_WITH_CARTON;
private String PRODUCT_CLASS;
private String PRODUCT_LINE;
private long QUANTITY_IN_CONTAINER;
private String QUOTE_LINE_SENT_FLAG;
private String QUOTE_MAX_QUANTITY;
private String QUOTE_MIN_QUANTITY;
private String QUOTE_ORDER_SENT;
private String REFUND_ON_ACCOUNT_FLAG;
private String REFUND_TO_ACCOUNT_FLAG;
private String REQUESTED_DELIVERY_DATE;
private String REQUESTED_SHIPMENT_DATE;
private String RESHIP_PARENT_LINE_KEY;
private String RESTRICT_SHIP_FROM_STORE;
private String RETURN_BY_GIFT_RECIPIENT;
private String RETURN_OH_KEY_FOR_EXCHANGE;
private String RETURN_REASON;
private String RETURN_REC_DUMMY_AMOUNT;
private String RETURN_RIS_NO;
private String RETURN_VPO_NO;
private String SEGMENT;
private String SEGMENT_TYPE; 
private String SELLER_ORGANIZATION_CODE; 
private String SENT_FOR_FRAUD_CHECK;
private String SHIPMENT_CARRIER_CODE;
private String SHIPMENT_CLOSED_FLAG;
private String SHIPMENT_CONTAINERIZED_FLAG;
private long SHIPMENT_CONTAINERIZED_QUANTITY;
private String SHIPMENT_CONTAINER_KEY;
private String SHIPMENT_CUSTOM_PACK_STATUS_DATE;
private String SHIPMENT_CUSTOM_SHIP_DATE;
private String SHIPMENT_DELIVERY_METHOD;
private double SHIPMENT_FREIGHT_CHARGE;
private String SHIPMENT_FULFILLMENT_TYPE;
private String SHIPMENT_INVOICE_COMPLETE;
private String SHIPMENT_KEY;
private String SHIPMENT_LINE_ACTUAL_SERIAL_NUMBER;
private long SHIPMENT_LINE_BACKROOM_PICKED_QTY;
private String SHIPMENT_LINE_BACKROOM_PICK_COMPLETE;
private String SHIPMENT_LINE_DESC;
private String SHIPMENT_LINE_KEY;
private long SHIPMENT_LINE_KIT_QTY;
private long SHIPMENT_LINE_NO;
private long SHIPMENT_LINE_ORIGINAL_QTY;
private long SHIPMENT_LINE_OVER_SHIP_QTY;
private String SHIPMENT_LINE_POS_RESERVATION_ID;
private String SHIPMENT_LINE_POS_SKU_NUMBER;
private long SHIPMENT_LINE_PRIME_LINE_NO;
private long SHIPMENT_LINE_QUANTITY;
private long SHIPMENT_LINE_RELEASE_NO;
private String SHIPMENT_LINE_SERIALIZED_ITEM_FLAG;
private long SHIPMENT_LINE_SUB_LINE_NO;
private String SHIPMENT_LINE_USED_VINTAGE_ITEM_FLAG;
private String SHIPMENT_LOS; 
private String SHIPMENT_MUST_SHIP_BEFORE;
private String SHIPMENT_NO;
private String SHIPMENT_PACKLIST_TYPE;
private String SHIPMENT_PENDING_RECEIPT_DATE;
private String SHIPMENT_PICKREQUEST_NO;
private String SHIPMENT_PICKUP_STORE_ID;
private String SHIPMENT_PIPELINE_KEY;
private long SHIPMENT_PLACED_QUANTITY;
private String SHIPMENT_POS_SALES_TICKET_NO;
private String SHIPMENT_RECEIVING_NODE;
private String SHIPMENT_REQUESTED_CARRIER_CODE;
private String SHIPMENT_SHIPNODE_KEY;
private String SHIPMENT_SHIP_DATE;
private String SHIPMENT_STATUS;
private String SHIPMENT_STATUS_DATE;
private String SHIPMENT_STATUS_NAME;
private long SHIPMENT_TOTAL_QUANTITY;
private String SHIPMENT_TYPE;
private long SHIPMENT_UNPLACED_QUANTITY;
private double SHIPMENT_VOLUME;
private String SHIPMENT_VOLUME_UOM;
private double SHIPMENT_WEIGHT;
private String SHIPMENT_WEIGHT_UOM;
private String SHIP_FROM_ADDRESS_LINE1;
private String SHIP_FROM_COMPANY;
private String SHIP_TO_COMPANY;
private String SHIP_TO_STORE_ID;
private String SOURCING_CLASSIFICATION;
private String STORE_CREDIT_FLAG;
private String TAX_PRODUCT_CODE;
private long TOTAL_ADJUSTMENT_AMOUNT;
private String TO_CITY;
private String TO_STATE;
private String TRACKING_NO;
private long UNIT_COST;
private double UNIT_PRICE;
private String UOM;
public String getCONTAINER_DETAILS_KEY() {
	return CONTAINER_DETAILS_KEY;
}
public void setCONTAINER_DETAILS_KEY(String cONTAINER_DETAILS_KEY) {
	CONTAINER_DETAILS_KEY = cONTAINER_DETAILS_KEY;
}
public String getACTUAL_CARRIER_CODE_WHILE_SHIPPING() {
	return ACTUAL_CARRIER_CODE_WHILE_SHIPPING;
}
public void setACTUAL_CARRIER_CODE_WHILE_SHIPPING(String aCTUAL_CARRIER_CODE_WHILE_SHIPPING) {
	ACTUAL_CARRIER_CODE_WHILE_SHIPPING = aCTUAL_CARRIER_CODE_WHILE_SHIPPING;
}
public String getACTUAL_DELIVERY_DATE() {
	return ACTUAL_DELIVERY_DATE;
}
public void setACTUAL_DELIVERY_DATE(String aCTUAL_DELIVERY_DATE) {
	ACTUAL_DELIVERY_DATE = aCTUAL_DELIVERY_DATE;
}
public double getACTUAL_FREIGHT_CHARGE() {
	return ACTUAL_FREIGHT_CHARGE;
}
public void setACTUAL_FREIGHT_CHARGE(double aCTUAL_FREIGHT_CHARGE) {
	ACTUAL_FREIGHT_CHARGE = aCTUAL_FREIGHT_CHARGE;
}
public String getACTUAL_SHIPMENT_DATE() {
	return ACTUAL_SHIPMENT_DATE;
}
public void setACTUAL_SHIPMENT_DATE(String aCTUAL_SHIPMENT_DATE) {
	ACTUAL_SHIPMENT_DATE = aCTUAL_SHIPMENT_DATE;
}
public String getALLOCATION_RULE_ID() {
	return ALLOCATION_RULE_ID;
}
public void setALLOCATION_RULE_ID(String aLLOCATION_RULE_ID) {
	ALLOCATION_RULE_ID = aLLOCATION_RULE_ID;
}
public String getAUTO_CANCEL_DATE() {
	return AUTO_CANCEL_DATE;
}
public void setAUTO_CANCEL_DATE(String aUTO_CANCEL_DATE) {
	AUTO_CANCEL_DATE = aUTO_CANCEL_DATE;
}
public String getBUNDLE_FULFILLMENT_MODE() {
	return BUNDLE_FULFILLMENT_MODE;
}
public void setBUNDLE_FULFILLMENT_MODE(String bUNDLE_FULFILLMENT_MODE) {
	BUNDLE_FULFILLMENT_MODE = bUNDLE_FULFILLMENT_MODE;
}
public String getBUNDLE_PARENT_ORDER_LINE_KEY() {
	return BUNDLE_PARENT_ORDER_LINE_KEY;
}
public void setBUNDLE_PARENT_ORDER_LINE_KEY(String bUNDLE_PARENT_ORDER_LINE_KEY) {
	BUNDLE_PARENT_ORDER_LINE_KEY = bUNDLE_PARENT_ORDER_LINE_KEY;
}
public String getBUYER_ORGANIZATION_CODE() {
	return BUYER_ORGANIZATION_CODE;
}
public void setBUYER_ORGANIZATION_CODE(String bUYER_ORGANIZATION_CODE) {
	BUYER_ORGANIZATION_CODE = bUYER_ORGANIZATION_CODE;
}
public String getCANNOT_COMPLETE_AFTER_DATE() {
	return CANNOT_COMPLETE_AFTER_DATE;
}
public void setCANNOT_COMPLETE_AFTER_DATE(String cANNOT_COMPLETE_AFTER_DATE) {
	CANNOT_COMPLETE_AFTER_DATE = cANNOT_COMPLETE_AFTER_DATE;
}
public String getCANNOT_COMPLETE_BEFORE_DATE() {
	return CANNOT_COMPLETE_BEFORE_DATE;
}
public void setCANNOT_COMPLETE_BEFORE_DATE(String cANNOT_COMPLETE_BEFORE_DATE) {
	CANNOT_COMPLETE_BEFORE_DATE = cANNOT_COMPLETE_BEFORE_DATE;
}
public String getCARRIER_PICKUP_TIME() {
	return CARRIER_PICKUP_TIME;
}
public void setCARRIER_PICKUP_TIME(String cARRIER_PICKUP_TIME) {
	CARRIER_PICKUP_TIME = cARRIER_PICKUP_TIME;
}
public String getCHAINED_FROM_ORDER_HEADER_KEY() {
	return CHAINED_FROM_ORDER_HEADER_KEY;
}
public void setCHAINED_FROM_ORDER_HEADER_KEY(String cHAINED_FROM_ORDER_HEADER_KEY) {
	CHAINED_FROM_ORDER_HEADER_KEY = cHAINED_FROM_ORDER_HEADER_KEY;
}
public String getCHAINED_FROM_ORDER_LINE_KEY() {
	return CHAINED_FROM_ORDER_LINE_KEY;
}
public void setCHAINED_FROM_ORDER_LINE_KEY(String cHAINED_FROM_ORDER_LINE_KEY) {
	CHAINED_FROM_ORDER_LINE_KEY = cHAINED_FROM_ORDER_LINE_KEY;
}
public String getCHAIN_TYPE() {
	return CHAIN_TYPE;
}
public void setCHAIN_TYPE(String cHAIN_TYPE) {
	CHAIN_TYPE = cHAIN_TYPE;
}
public String getCM_ITEM_CONDITION_MESSAGE() {
	return CM_ITEM_CONDITION_MESSAGE;
}
public void setCM_ITEM_CONDITION_MESSAGE(String cM_ITEM_CONDITION_MESSAGE) {
	CM_ITEM_CONDITION_MESSAGE = cM_ITEM_CONDITION_MESSAGE;
}
public String getCM_PROMISE_DATE() {
	return CM_PROMISE_DATE;
}
public void setCM_PROMISE_DATE(String cM_PROMISE_DATE) {
	CM_PROMISE_DATE = cM_PROMISE_DATE;
}
public String getCM_PROMISE_MESSAGE() {
	return CM_PROMISE_MESSAGE;
}
public void setCM_PROMISE_MESSAGE(String cM_PROMISE_MESSAGE) {
	CM_PROMISE_MESSAGE = cM_PROMISE_MESSAGE;
}
public long getCOMMITTED_QUANTITY() {
	return COMMITTED_QUANTITY;
}
public void setCOMMITTED_QUANTITY(long cOMMITTED_QUANTITY) {
	COMMITTED_QUANTITY = cOMMITTED_QUANTITY;
}
public String getCONDITION_VARIABLE_1() {
	return CONDITION_VARIABLE_1;
}
public void setCONDITION_VARIABLE_1(String cONDITION_VARIABLE_1) {
	CONDITION_VARIABLE_1 = cONDITION_VARIABLE_1;
}
public String getCONDITION_VARIABLE_2() {
	return CONDITION_VARIABLE_2;
}
public void setCONDITION_VARIABLE_2(String cONDITION_VARIABLE_2) {
	CONDITION_VARIABLE_2 = cONDITION_VARIABLE_2;
}
public String getCONTAINER_CUSTOM_STATUS() {
	return CONTAINER_CUSTOM_STATUS;
}
public void setCONTAINER_CUSTOM_STATUS(String cONTAINER_CUSTOM_STATUS) {
	CONTAINER_CUSTOM_STATUS = cONTAINER_CUSTOM_STATUS;
}
public double getCONTAINER_GROSS_WEIGHT() {
	return CONTAINER_GROSS_WEIGHT;
}
public void setCONTAINER_GROSS_WEIGHT(double cONTAINER_GROSS_WEIGHT) {
	CONTAINER_GROSS_WEIGHT = cONTAINER_GROSS_WEIGHT;
}
public String getCONTAINER_GROSS_WEIGHT_UOM() {
	return CONTAINER_GROSS_WEIGHT_UOM;
}
public void setCONTAINER_GROSS_WEIGHT_UOM(String cONTAINER_GROSS_WEIGHT_UOM) {
	CONTAINER_GROSS_WEIGHT_UOM = cONTAINER_GROSS_WEIGHT_UOM;
}
public String getCONTAINER_MULTIBOX_DESC() {
	return CONTAINER_MULTIBOX_DESC;
}
public void setCONTAINER_MULTIBOX_DESC(String cONTAINER_MULTIBOX_DESC) {
	CONTAINER_MULTIBOX_DESC = cONTAINER_MULTIBOX_DESC;
}
public String getCONTAINER_MULTI_BOX_ID() {
	return CONTAINER_MULTI_BOX_ID;
}
public void setCONTAINER_MULTI_BOX_ID(String cONTAINER_MULTI_BOX_ID) {
	CONTAINER_MULTI_BOX_ID = cONTAINER_MULTI_BOX_ID;
}
public String getCONTAINER_NO() {
	return CONTAINER_NO;
}
public void setCONTAINER_NO(String cONTAINER_NO) {
	CONTAINER_NO = cONTAINER_NO;
}
public String getCONTAINER_SHIP_DATE() {
	return CONTAINER_SHIP_DATE;
}
public void setCONTAINER_SHIP_DATE(String cONTAINER_SHIP_DATE) {
	CONTAINER_SHIP_DATE = cONTAINER_SHIP_DATE;
}
public String getCONTAINER_STATUS_DATE() {
	return CONTAINER_STATUS_DATE;
}
public void setCONTAINER_STATUS_DATE(String cONTAINER_STATUS_DATE) {
	CONTAINER_STATUS_DATE = cONTAINER_STATUS_DATE;
}
public String getCREATEPROGID_CONTAINER_DETAILS() {
	return CREATEPROGID_CONTAINER_DETAILS;
}
public void setCREATEPROGID_CONTAINER_DETAILS(String cREATEPROGID_CONTAINER_DETAILS) {
	CREATEPROGID_CONTAINER_DETAILS = cREATEPROGID_CONTAINER_DETAILS;
}
public String getCREATEPROGID_ORDER() {
	return CREATEPROGID_ORDER;
}
public void setCREATEPROGID_ORDER(String cREATEPROGID_ORDER) {
	CREATEPROGID_ORDER = cREATEPROGID_ORDER;
}
public String getCREATEPROGID_ORDER_LINE() {
	return CREATEPROGID_ORDER_LINE;
}
public void setCREATEPROGID_ORDER_LINE(String cREATEPROGID_ORDER_LINE) {
	CREATEPROGID_ORDER_LINE = cREATEPROGID_ORDER_LINE;
}
public String getCREATEPROGID_SHIPMENT() {
	return CREATEPROGID_SHIPMENT;
}
public void setCREATEPROGID_SHIPMENT(String cREATEPROGID_SHIPMENT) {
	CREATEPROGID_SHIPMENT = cREATEPROGID_SHIPMENT;
}
public String getCREATEPROGID_SHIPMENT_CONTAINER() {
	return CREATEPROGID_SHIPMENT_CONTAINER;
}
public void setCREATEPROGID_SHIPMENT_CONTAINER(String cREATEPROGID_SHIPMENT_CONTAINER) {
	CREATEPROGID_SHIPMENT_CONTAINER = cREATEPROGID_SHIPMENT_CONTAINER;
}
public String getCREATEPROGID_SHIPMENT_LINE() {
	return CREATEPROGID_SHIPMENT_LINE;
}
public void setCREATEPROGID_SHIPMENT_LINE(String cREATEPROGID_SHIPMENT_LINE) {
	CREATEPROGID_SHIPMENT_LINE = cREATEPROGID_SHIPMENT_LINE;
}
public String getCREATETS_CONTAINER_DETAILS() {
	return CREATETS_CONTAINER_DETAILS;
}
public void setCREATETS_CONTAINER_DETAILS(String cREATETS_CONTAINER_DETAILS) {
	CREATETS_CONTAINER_DETAILS = cREATETS_CONTAINER_DETAILS;
}
public String getCREATETS_ORDER() {
	return CREATETS_ORDER;
}
public void setCREATETS_ORDER(String cREATETS_ORDER) {
	CREATETS_ORDER = cREATETS_ORDER;
}
public String getCREATETS_ORDER_LINE() {
	return CREATETS_ORDER_LINE;
}
public void setCREATETS_ORDER_LINE(String cREATETS_ORDER_LINE) {
	CREATETS_ORDER_LINE = cREATETS_ORDER_LINE;
}
public String getCREATETS_SHIPMENT() {
	return CREATETS_SHIPMENT;
}
public void setCREATETS_SHIPMENT(String cREATETS_SHIPMENT) {
	CREATETS_SHIPMENT = cREATETS_SHIPMENT;
}
public String getCREATETS_SHIPMENT_CONTAINER() {
	return CREATETS_SHIPMENT_CONTAINER;
}
public void setCREATETS_SHIPMENT_CONTAINER(String cREATETS_SHIPMENT_CONTAINER) {
	CREATETS_SHIPMENT_CONTAINER = cREATETS_SHIPMENT_CONTAINER;
}
public String getCREATETS_SHIPMENT_LINE() {
	return CREATETS_SHIPMENT_LINE;
}
public void setCREATETS_SHIPMENT_LINE(String cREATETS_SHIPMENT_LINE) {
	CREATETS_SHIPMENT_LINE = cREATETS_SHIPMENT_LINE;
}
public String getCREATEUSERID_CONTAINER_DETAILS() {
	return CREATEUSERID_CONTAINER_DETAILS;
}
public void setCREATEUSERID_CONTAINER_DETAILS(String cREATEUSERID_CONTAINER_DETAILS) {
	CREATEUSERID_CONTAINER_DETAILS = cREATEUSERID_CONTAINER_DETAILS;
}
public String getCREATEUSERID_ORDER() {
	return CREATEUSERID_ORDER;
}
public void setCREATEUSERID_ORDER(String cREATEUSERID_ORDER) {
	CREATEUSERID_ORDER = cREATEUSERID_ORDER;
}
public String getCREATEUSERID_ORDER_LINE() {
	return CREATEUSERID_ORDER_LINE;
}
public void setCREATEUSERID_ORDER_LINE(String cREATEUSERID_ORDER_LINE) {
	CREATEUSERID_ORDER_LINE = cREATEUSERID_ORDER_LINE;
}
public String getCREATEUSERID_SHIPMENT() {
	return CREATEUSERID_SHIPMENT;
}
public void setCREATEUSERID_SHIPMENT(String cREATEUSERID_SHIPMENT) {
	CREATEUSERID_SHIPMENT = cREATEUSERID_SHIPMENT;
}
public String getCREATEUSERID_SHIPMENT_CONTAINER() {
	return CREATEUSERID_SHIPMENT_CONTAINER;
}
public void setCREATEUSERID_SHIPMENT_CONTAINER(String cREATEUSERID_SHIPMENT_CONTAINER) {
	CREATEUSERID_SHIPMENT_CONTAINER = cREATEUSERID_SHIPMENT_CONTAINER;
}
public String getCREATEUSERID_SHIPMENT_LINE() {
	return CREATEUSERID_SHIPMENT_LINE;
}
public void setCREATEUSERID_SHIPMENT_LINE(String cREATEUSERID_SHIPMENT_LINE) {
	CREATEUSERID_SHIPMENT_LINE = cREATEUSERID_SHIPMENT_LINE;
}
public String getCUSTOMER_ZIP_CODE() {
	return CUSTOMER_ZIP_CODE;
}
public void setCUSTOMER_ZIP_CODE(String cUSTOMER_ZIP_CODE) {
	CUSTOMER_ZIP_CODE = cUSTOMER_ZIP_CODE;
}
public String getCUSTOM_BACKORDER_EMAIL_SENT_FLAG() {
	return CUSTOM_BACKORDER_EMAIL_SENT_FLAG;
}
public void setCUSTOM_BACKORDER_EMAIL_SENT_FLAG(String cUSTOM_BACKORDER_EMAIL_SENT_FLAG) {
	CUSTOM_BACKORDER_EMAIL_SENT_FLAG = cUSTOM_BACKORDER_EMAIL_SENT_FLAG;
}
public String getCUSTOM_CURRENCY_CONVERSION_RATE() {
	return CUSTOM_CURRENCY_CONVERSION_RATE;
}
public void setCUSTOM_CURRENCY_CONVERSION_RATE(String cUSTOM_CURRENCY_CONVERSION_RATE) {
	CUSTOM_CURRENCY_CONVERSION_RATE = cUSTOM_CURRENCY_CONVERSION_RATE;
}
public String getCUSTOM_IS_PO_RESERVED() {
	return CUSTOM_IS_PO_RESERVED;
}
public void setCUSTOM_IS_PO_RESERVED(String cUSTOM_IS_PO_RESERVED) {
	CUSTOM_IS_PO_RESERVED = cUSTOM_IS_PO_RESERVED;
}
public String getCUSTOM_IS_PRICING_STRATEGY_COMP() {
	return CUSTOM_IS_PRICING_STRATEGY_COMP;
}
public void setCUSTOM_IS_PRICING_STRATEGY_COMP(String cUSTOM_IS_PRICING_STRATEGY_COMP) {
	CUSTOM_IS_PRICING_STRATEGY_COMP = cUSTOM_IS_PRICING_STRATEGY_COMP;
}
public String getCUSTOM_LINE_SERIAL_NUMBER() {
	return CUSTOM_LINE_SERIAL_NUMBER;
}
public void setCUSTOM_LINE_SERIAL_NUMBER(String cUSTOM_LINE_SERIAL_NUMBER) {
	CUSTOM_LINE_SERIAL_NUMBER = cUSTOM_LINE_SERIAL_NUMBER;
}
public String getCUSTOM_NON_HJ_LINE() {
	return CUSTOM_NON_HJ_LINE;
}
public void setCUSTOM_NON_HJ_LINE(String cUSTOM_NON_HJ_LINE) {
	CUSTOM_NON_HJ_LINE = cUSTOM_NON_HJ_LINE;
}
public String getDELIVERY_METHOD() {
	return DELIVERY_METHOD;
}
public void setDELIVERY_METHOD(String dELIVERY_METHOD) {
	DELIVERY_METHOD = dELIVERY_METHOD;
}
public String getDEPENDENT_ON_LINE_KEY() {
	return DEPENDENT_ON_LINE_KEY;
}
public void setDEPENDENT_ON_LINE_KEY(String dEPENDENT_ON_LINE_KEY) {
	DEPENDENT_ON_LINE_KEY = dEPENDENT_ON_LINE_KEY;
}
public String getDERIVED_FROM_ORDER_HEADER_KEY() {
	return DERIVED_FROM_ORDER_HEADER_KEY;
}
public void setDERIVED_FROM_ORDER_HEADER_KEY(String dERIVED_FROM_ORDER_HEADER_KEY) {
	DERIVED_FROM_ORDER_HEADER_KEY = dERIVED_FROM_ORDER_HEADER_KEY;
}
public String getDERIVED_FROM_ORDER_LINE_KEY() {
	return DERIVED_FROM_ORDER_LINE_KEY;
}
public void setDERIVED_FROM_ORDER_LINE_KEY(String dERIVED_FROM_ORDER_LINE_KEY) {
	DERIVED_FROM_ORDER_LINE_KEY = dERIVED_FROM_ORDER_LINE_KEY;
}
public String getDERIVED_FROM_ORDER_RELEASE_KEY() {
	return DERIVED_FROM_ORDER_RELEASE_KEY;
}
public void setDERIVED_FROM_ORDER_RELEASE_KEY(String dERIVED_FROM_ORDER_RELEASE_KEY) {
	DERIVED_FROM_ORDER_RELEASE_KEY = dERIVED_FROM_ORDER_RELEASE_KEY;
}
public String getDISPLAY_FOREIGN_CURRENCY() {
	return DISPLAY_FOREIGN_CURRENCY;
}
public void setDISPLAY_FOREIGN_CURRENCY(String dISPLAY_FOREIGN_CURRENCY) {
	DISPLAY_FOREIGN_CURRENCY = dISPLAY_FOREIGN_CURRENCY;
}
public String getDISPOSITION_CODE() {
	return DISPOSITION_CODE;
}
public void setDISPOSITION_CODE(String dISPOSITION_CODE) {
	DISPOSITION_CODE = dISPOSITION_CODE;
}
public String getDOCUMENT_TYPE() {
	return DOCUMENT_TYPE;
}
public void setDOCUMENT_TYPE(String dOCUMENT_TYPE) {
	DOCUMENT_TYPE = dOCUMENT_TYPE;
}
public String getDRAFT_ORDER_FLAG() {
	return DRAFT_ORDER_FLAG;
}
public void setDRAFT_ORDER_FLAG(String dRAFT_ORDER_FLAG) {
	DRAFT_ORDER_FLAG = dRAFT_ORDER_FLAG;
}
public String getEARLIEST_DELIVERY_DATE() {
	return EARLIEST_DELIVERY_DATE;
}
public void setEARLIEST_DELIVERY_DATE(String eARLIEST_DELIVERY_DATE) {
	EARLIEST_DELIVERY_DATE = eARLIEST_DELIVERY_DATE;
}
public String getEARLIEST_SHIP_DATE() {
	return EARLIEST_SHIP_DATE;
}
public void setEARLIEST_SHIP_DATE(String eARLIEST_SHIP_DATE) {
	EARLIEST_SHIP_DATE = eARLIEST_SHIP_DATE;
}
public String getEMPLOYEE_ORDER() {
	return EMPLOYEE_ORDER;
}
public void setEMPLOYEE_ORDER(String eMPLOYEE_ORDER) {
	EMPLOYEE_ORDER = eMPLOYEE_ORDER;
}
public String getENTERPRISE_CODE() {
	return ENTERPRISE_CODE;
}
public void setENTERPRISE_CODE(String eNTERPRISE_CODE) {
	ENTERPRISE_CODE = eNTERPRISE_CODE;
}
public String getENTRY_TYPE() {
	return ENTRY_TYPE;
}
public void setENTRY_TYPE(String eNTRY_TYPE) {
	ENTRY_TYPE = eNTRY_TYPE;
}
public double getESTIMATED_PRICE() {
	return ESTIMATED_PRICE;
}
public void setESTIMATED_PRICE(double eSTIMATED_PRICE) {
	ESTIMATED_PRICE = eSTIMATED_PRICE;
}
public String getEXCHANGE_TYPE() {
	return EXCHANGE_TYPE;
}
public void setEXCHANGE_TYPE(String eXCHANGE_TYPE) {
	EXCHANGE_TYPE = eXCHANGE_TYPE;
}
public String getEXPECTED_DELIVERY_DATE() {
	return EXPECTED_DELIVERY_DATE;
}
public void setEXPECTED_DELIVERY_DATE(String eXPECTED_DELIVERY_DATE) {
	EXPECTED_DELIVERY_DATE = eXPECTED_DELIVERY_DATE;
}
public String getEXPECTED_SHIPMENT_DATE() {
	return EXPECTED_SHIPMENT_DATE;
}
public void setEXPECTED_SHIPMENT_DATE(String eXPECTED_SHIPMENT_DATE) {
	EXPECTED_SHIPMENT_DATE = eXPECTED_SHIPMENT_DATE;
}
public long getFILL_QUANTITY() {
	return FILL_QUANTITY;
}
public void setFILL_QUANTITY(long fILL_QUANTITY) {
	FILL_QUANTITY = fILL_QUANTITY;
}
public String getFREE_GIFT_ITEM_FLAG() {
	return FREE_GIFT_ITEM_FLAG;
}
public void setFREE_GIFT_ITEM_FLAG(String fREE_GIFT_ITEM_FLAG) {
	FREE_GIFT_ITEM_FLAG = fREE_GIFT_ITEM_FLAG;
}
public String getFROM_CITY() {
	return FROM_CITY;
}
public void setFROM_CITY(String fROM_CITY) {
	FROM_CITY = fROM_CITY;
}
public String getFROM_STATE() {
	return FROM_STATE;
}
public void setFROM_STATE(String fROM_STATE) {
	FROM_STATE = fROM_STATE;
}
public String getGCSS_STUDENT_ID() {
	return GCSS_STUDENT_ID;
}
public void setGCSS_STUDENT_ID(String gCSS_STUDENT_ID) {
	GCSS_STUDENT_ID = gCSS_STUDENT_ID;
}
public String getGIFT_ORDER() {
	return GIFT_ORDER;
}
public void setGIFT_ORDER(String gIFT_ORDER) {
	GIFT_ORDER = gIFT_ORDER;
}
public String getGLOBAL_MSN() {
	return GLOBAL_MSN;
}
public void setGLOBAL_MSN(String gLOBAL_MSN) {
	GLOBAL_MSN = gLOBAL_MSN;
}
public String getHAS_DERIVED_CHILD() {
	return HAS_DERIVED_CHILD;
}
public void setHAS_DERIVED_CHILD(String hAS_DERIVED_CHILD) {
	HAS_DERIVED_CHILD = hAS_DERIVED_CHILD;
}
public String getHAS_DERIVED_PARENT() {
	return HAS_DERIVED_PARENT;
}
public void setHAS_DERIVED_PARENT(String hAS_DERIVED_PARENT) {
	HAS_DERIVED_PARENT = hAS_DERIVED_PARENT;
}
public String getINTENTIONAL_BACKORDER() {
	return INTENTIONAL_BACKORDER;
}
public void setINTENTIONAL_BACKORDER(String iNTENTIONAL_BACKORDER) {
	INTENTIONAL_BACKORDER = iNTENTIONAL_BACKORDER;
}
public String getINTL_ORDER_DUTY() {
	return INTL_ORDER_DUTY;
}
public void setINTL_ORDER_DUTY(String iNTL_ORDER_DUTY) {
	INTL_ORDER_DUTY = iNTL_ORDER_DUTY;
}
public String getINTL_ORDER_HANDLING() {
	return INTL_ORDER_HANDLING;
}
public void setINTL_ORDER_HANDLING(String iNTL_ORDER_HANDLING) {
	INTL_ORDER_HANDLING = iNTL_ORDER_HANDLING;
}
public String getINTL_ORDER_VAT() {
	return INTL_ORDER_VAT;
}
public void setINTL_ORDER_VAT(String iNTL_ORDER_VAT) {
	INTL_ORDER_VAT = iNTL_ORDER_VAT;
}
public String getINTL_WEB_ORDER_NO() {
	return INTL_WEB_ORDER_NO;
}
public void setINTL_WEB_ORDER_NO(String iNTL_WEB_ORDER_NO) {
	INTL_WEB_ORDER_NO = iNTL_WEB_ORDER_NO;
}
public String getINT_ORDER_GRAND_TOTAL() {
	return INT_ORDER_GRAND_TOTAL;
}
public void setINT_ORDER_GRAND_TOTAL(String iNT_ORDER_GRAND_TOTAL) {
	INT_ORDER_GRAND_TOTAL = iNT_ORDER_GRAND_TOTAL;
}
public String getINT_ORDER_SHIPPING() {
	return INT_ORDER_SHIPPING;
}
public void setINT_ORDER_SHIPPING(String iNT_ORDER_SHIPPING) {
	INT_ORDER_SHIPPING = iNT_ORDER_SHIPPING;
}
public String getINVC_UPDATED_DATE() {
	return INVC_UPDATED_DATE;
}
public void setINVC_UPDATED_DATE(String iNVC_UPDATED_DATE) {
	INVC_UPDATED_DATE = iNVC_UPDATED_DATE;
}
public double getINVOICED_EXTENDED_PRICE() {
	return INVOICED_EXTENDED_PRICE;
}
public void setINVOICED_EXTENDED_PRICE(double iNVOICED_EXTENDED_PRICE) {
	INVOICED_EXTENDED_PRICE = iNVOICED_EXTENDED_PRICE;
}
public double getINVOICED_LINE_TOTAL() {
	return INVOICED_LINE_TOTAL;
}
public void setINVOICED_LINE_TOTAL(double iNVOICED_LINE_TOTAL) {
	INVOICED_LINE_TOTAL = iNVOICED_LINE_TOTAL;
}
public String getIS_COST_OVERRIDDEN() {
	return IS_COST_OVERRIDDEN;
}
public void setIS_COST_OVERRIDDEN(String iS_COST_OVERRIDDEN) {
	IS_COST_OVERRIDDEN = iS_COST_OVERRIDDEN;
}
public String getIS_FIRM_PREDEFINED_NODE() {
	return IS_FIRM_PREDEFINED_NODE;
}
public void setIS_FIRM_PREDEFINED_NODE(String iS_FIRM_PREDEFINED_NODE) {
	IS_FIRM_PREDEFINED_NODE = iS_FIRM_PREDEFINED_NODE;
}
public String getIS_FORCED_SOURCED_LINE() {
	return IS_FORCED_SOURCED_LINE;
}
public void setIS_FORCED_SOURCED_LINE(String iS_FORCED_SOURCED_LINE) {
	IS_FORCED_SOURCED_LINE = iS_FORCED_SOURCED_LINE;
}
public String getIS_NEWLY_ADDED_LINE() {
	return IS_NEWLY_ADDED_LINE;
}
public void setIS_NEWLY_ADDED_LINE(String iS_NEWLY_ADDED_LINE) {
	IS_NEWLY_ADDED_LINE = iS_NEWLY_ADDED_LINE;
}
public String getIS_STORE_CLEARANCE() {
	return IS_STORE_CLEARANCE;
}
public void setIS_STORE_CLEARANCE(String iS_STORE_CLEARANCE) {
	IS_STORE_CLEARANCE = iS_STORE_CLEARANCE;
}
public String getIS_WARRANTY_FLAG() {
	return IS_WARRANTY_FLAG;
}
public void setIS_WARRANTY_FLAG(String iS_WARRANTY_FLAG) {
	IS_WARRANTY_FLAG = iS_WARRANTY_FLAG;
}
public String getITEM_GROUP_CODE() {
	return ITEM_GROUP_CODE;
}
public void setITEM_GROUP_CODE(String iTEM_GROUP_CODE) {
	ITEM_GROUP_CODE = iTEM_GROUP_CODE;
}
public String getITEM_ID() {
	return ITEM_ID;
}
public void setITEM_ID(String iTEM_ID) {
	ITEM_ID = iTEM_ID;
}
public String getKIT_CODE() {
	return KIT_CODE;
}
public void setKIT_CODE(String kIT_CODE) {
	KIT_CODE = kIT_CODE;
}
public String getLINE_CARRIER_SERVICE_CODE() {
	return LINE_CARRIER_SERVICE_CODE;
}
public void setLINE_CARRIER_SERVICE_CODE(String lINE_CARRIER_SERVICE_CODE) {
	LINE_CARRIER_SERVICE_CODE = lINE_CARRIER_SERVICE_CODE;
}
public String getLINE_FTC_EXCEMPT_FLAG() {
	return LINE_FTC_EXCEMPT_FLAG;
}
public void setLINE_FTC_EXCEMPT_FLAG(String lINE_FTC_EXCEMPT_FLAG) {
	LINE_FTC_EXCEMPT_FLAG = lINE_FTC_EXCEMPT_FLAG;
}
public String getLINE_FULFILLED_NODE() {
	return LINE_FULFILLED_NODE;
}
public void setLINE_FULFILLED_NODE(String lINE_FULFILLED_NODE) {
	LINE_FULFILLED_NODE = lINE_FULFILLED_NODE;
}
public String getLINE_FULFILLMENT_TYPE() {
	return LINE_FULFILLMENT_TYPE;
}
public void setLINE_FULFILLMENT_TYPE(String lINE_FULFILLMENT_TYPE) {
	LINE_FULFILLMENT_TYPE = lINE_FULFILLMENT_TYPE;
}
public String getLINE_GIFT_MESSAGE() {
	return LINE_GIFT_MESSAGE;
}
public void setLINE_GIFT_MESSAGE(String lINE_GIFT_MESSAGE) {
	LINE_GIFT_MESSAGE = lINE_GIFT_MESSAGE;
}
public String getLINE_GIFT_WRAP() {
	return LINE_GIFT_WRAP;
}
public void setLINE_GIFT_WRAP(String lINE_GIFT_WRAP) {
	LINE_GIFT_WRAP = lINE_GIFT_WRAP;
}
public String getLINE_HAS_BACKORDERED() {
	return LINE_HAS_BACKORDERED;
}
public void setLINE_HAS_BACKORDERED(String lINE_HAS_BACKORDERED) {
	LINE_HAS_BACKORDERED = lINE_HAS_BACKORDERED;
}
public double getLINE_INVENTORY_COST() {
	return LINE_INVENTORY_COST;
}
public void setLINE_INVENTORY_COST(double lINE_INVENTORY_COST) {
	LINE_INVENTORY_COST = lINE_INVENTORY_COST;
}
public long getLINE_INVOICED_PRICED_QTY() {
	return LINE_INVOICED_PRICED_QTY;
}
public void setLINE_INVOICED_PRICED_QTY(long lINE_INVOICED_PRICED_QTY) {
	LINE_INVOICED_PRICED_QTY = lINE_INVOICED_PRICED_QTY;
}
public String getLINE_INVOICE_COMPLETE_FLAG() {
	return LINE_INVOICE_COMPLETE_FLAG;
}
public void setLINE_INVOICE_COMPLETE_FLAG(String lINE_INVOICE_COMPLETE_FLAG) {
	LINE_INVOICE_COMPLETE_FLAG = lINE_INVOICE_COMPLETE_FLAG;
}
public String getLINE_IS_AMOUNT_COLLECTED() {
	return LINE_IS_AMOUNT_COLLECTED;
}
public void setLINE_IS_AMOUNT_COLLECTED(String lINE_IS_AMOUNT_COLLECTED) {
	LINE_IS_AMOUNT_COLLECTED = lINE_IS_AMOUNT_COLLECTED;
}
public String getLINE_IS_STORE_FULFILLED() {
	return LINE_IS_STORE_FULFILLED;
}
public void setLINE_IS_STORE_FULFILLED(String lINE_IS_STORE_FULFILLED) {
	LINE_IS_STORE_FULFILLED = lINE_IS_STORE_FULFILLED;
}
public double getLINE_ITEM_WEIGHT() {
	return LINE_ITEM_WEIGHT;
}
public void setLINE_ITEM_WEIGHT(double lINE_ITEM_WEIGHT) {
	LINE_ITEM_WEIGHT = lINE_ITEM_WEIGHT;
}
public String getLINE_ITEM_WEIGHT_UOM() {
	return LINE_ITEM_WEIGHT_UOM;
}
public void setLINE_ITEM_WEIGHT_UOM(String lINE_ITEM_WEIGHT_UOM) {
	LINE_ITEM_WEIGHT_UOM = lINE_ITEM_WEIGHT_UOM;
}
public long getLINE_KIT_QTY() {
	return LINE_KIT_QTY;
}
public void setLINE_KIT_QTY(long lINE_KIT_QTY) {
	LINE_KIT_QTY = lINE_KIT_QTY;
}
public double getLINE_LIST_PRICE() {
	return LINE_LIST_PRICE;
}
public void setLINE_LIST_PRICE(double lINE_LIST_PRICE) {
	LINE_LIST_PRICE = lINE_LIST_PRICE;
}
public String getLINE_LOS() {
	return LINE_LOS;
}
public void setLINE_LOS(String lINE_LOS) {
	LINE_LOS = lINE_LOS;
}
public String getLINE_NODE_AT_ORIGIN() {
	return LINE_NODE_AT_ORIGIN;
}
public void setLINE_NODE_AT_ORIGIN(String lINE_NODE_AT_ORIGIN) {
	LINE_NODE_AT_ORIGIN = lINE_NODE_AT_ORIGIN;
}
public long getLINE_ORIGINAL_ORDERED_QTY() {
	return LINE_ORIGINAL_ORDERED_QTY;
}
public void setLINE_ORIGINAL_ORDERED_QTY(long lINE_ORIGINAL_ORDERED_QTY) {
	LINE_ORIGINAL_ORDERED_QTY = lINE_ORIGINAL_ORDERED_QTY;
}
public long getLINE_OTHER_CHARGES() {
	return LINE_OTHER_CHARGES;
}
public void setLINE_OTHER_CHARGES(long lINE_OTHER_CHARGES) {
	LINE_OTHER_CHARGES = lINE_OTHER_CHARGES;
}
public String getLINE_PIPE_LINE_KEY() {
	return LINE_PIPE_LINE_KEY;
}
public void setLINE_PIPE_LINE_KEY(String lINE_PIPE_LINE_KEY) {
	LINE_PIPE_LINE_KEY = lINE_PIPE_LINE_KEY;
}
public String getLINE_POS_70_TICKET_NO() {
	return LINE_POS_70_TICKET_NO;
}
public void setLINE_POS_70_TICKET_NO(String lINE_POS_70_TICKET_NO) {
	LINE_POS_70_TICKET_NO = lINE_POS_70_TICKET_NO;
}
public String getLINE_POS_SALES_TICKET_NO() {
	return LINE_POS_SALES_TICKET_NO;
}
public void setLINE_POS_SALES_TICKET_NO(String lINE_POS_SALES_TICKET_NO) {
	LINE_POS_SALES_TICKET_NO = lINE_POS_SALES_TICKET_NO;
}
public String getLINE_POS_SKU_NUMBER() {
	return LINE_POS_SKU_NUMBER;
}
public void setLINE_POS_SKU_NUMBER(String lINE_POS_SKU_NUMBER) {
	LINE_POS_SKU_NUMBER = lINE_POS_SKU_NUMBER;
}
public long getLINE_PRICING_QUANTITY() {
	return LINE_PRICING_QUANTITY;
}
public void setLINE_PRICING_QUANTITY(long lINE_PRICING_QUANTITY) {
	LINE_PRICING_QUANTITY = lINE_PRICING_QUANTITY;
}
public String getLINE_PROCURE_NODE() {
	return LINE_PROCURE_NODE;
}
public void setLINE_PROCURE_NODE(String lINE_PROCURE_NODE) {
	LINE_PROCURE_NODE = lINE_PROCURE_NODE;
}
public long getLINE_QTY_CANCELLED_IN_SPLIT() {
	return LINE_QTY_CANCELLED_IN_SPLIT;
}
public void setLINE_QTY_CANCELLED_IN_SPLIT(long lINE_QTY_CANCELLED_IN_SPLIT) {
	LINE_QTY_CANCELLED_IN_SPLIT = lINE_QTY_CANCELLED_IN_SPLIT;
}
public long getLINE_RECEIVED_QTY() {
	return LINE_RECEIVED_QTY;
}
public void setLINE_RECEIVED_QTY(long lINE_RECEIVED_QTY) {
	LINE_RECEIVED_QTY = lINE_RECEIVED_QTY;
}
public String getLINE_RECEIVING_NODE() {
	return LINE_RECEIVING_NODE;
}
public void setLINE_RECEIVING_NODE(String lINE_RECEIVING_NODE) {
	LINE_RECEIVING_NODE = lINE_RECEIVING_NODE;
}
public String getLINE_REQUESTED_DELIVERY_DATE() {
	return LINE_REQUESTED_DELIVERY_DATE;
}
public void setLINE_REQUESTED_DELIVERY_DATE(String lINE_REQUESTED_DELIVERY_DATE) {
	LINE_REQUESTED_DELIVERY_DATE = lINE_REQUESTED_DELIVERY_DATE;
}
public String getLINE_REQUESTED_SHIP_DATE() {
	return LINE_REQUESTED_SHIP_DATE;
}
public void setLINE_REQUESTED_SHIP_DATE(String lINE_REQUESTED_SHIP_DATE) {
	LINE_REQUESTED_SHIP_DATE = lINE_REQUESTED_SHIP_DATE;
}
public String getLINE_REQ_CANCEL_DATE() {
	return LINE_REQ_CANCEL_DATE;
}
public void setLINE_REQ_CANCEL_DATE(String lINE_REQ_CANCEL_DATE) {
	LINE_REQ_CANCEL_DATE = lINE_REQ_CANCEL_DATE;
}
public long getLINE_RESCHEDULE_REQ_COUNT() {
	return LINE_RESCHEDULE_REQ_COUNT;
}
public void setLINE_RESCHEDULE_REQ_COUNT(long lINE_RESCHEDULE_REQ_COUNT) {
	LINE_RESCHEDULE_REQ_COUNT = lINE_RESCHEDULE_REQ_COUNT;
}
public long getLINE_RETAIL_PRICE() {
	return LINE_RETAIL_PRICE;
}
public void setLINE_RETAIL_PRICE(long lINE_RETAIL_PRICE) {
	LINE_RETAIL_PRICE = lINE_RETAIL_PRICE;
}
public String getLINE_SCHEDULE_FAILURE_CODE() {
	return LINE_SCHEDULE_FAILURE_CODE;
}
public void setLINE_SCHEDULE_FAILURE_CODE(String lINE_SCHEDULE_FAILURE_CODE) {
	LINE_SCHEDULE_FAILURE_CODE = lINE_SCHEDULE_FAILURE_CODE;
}
public String getLINE_SERIAL_NO() {
	return LINE_SERIAL_NO;
}
public void setLINE_SERIAL_NO(String lINE_SERIAL_NO) {
	LINE_SERIAL_NO = lINE_SERIAL_NO;
}
public long getLINE_SHIPPED_QUANTITY() {
	return LINE_SHIPPED_QUANTITY;
}
public void setLINE_SHIPPED_QUANTITY(long lINE_SHIPPED_QUANTITY) {
	LINE_SHIPPED_QUANTITY = lINE_SHIPPED_QUANTITY;
}
public String getLINE_SHIP_ALONE_FLAG() {
	return LINE_SHIP_ALONE_FLAG;
}
public void setLINE_SHIP_ALONE_FLAG(String lINE_SHIP_ALONE_FLAG) {
	LINE_SHIP_ALONE_FLAG = lINE_SHIP_ALONE_FLAG;
}
public String getLINE_TAXABLE_FLAG() {
	return LINE_TAXABLE_FLAG;
}
public void setLINE_TAXABLE_FLAG(String lINE_TAXABLE_FLAG) {
	LINE_TAXABLE_FLAG = lINE_TAXABLE_FLAG;
}
public double getLINE_TAX_AMOUNT() {
	return LINE_TAX_AMOUNT;
}
public void setLINE_TAX_AMOUNT(double lINE_TAX_AMOUNT) {
	LINE_TAX_AMOUNT = lINE_TAX_AMOUNT;
}
public double getLINE_TOTAL() {
	return LINE_TOTAL;
}
public void setLINE_TOTAL(double lINE_TOTAL) {
	LINE_TOTAL = lINE_TOTAL;
}
public String getMIN_SHIP_BY_DATE() {
	return MIN_SHIP_BY_DATE;
}
public void setMIN_SHIP_BY_DATE(String mIN_SHIP_BY_DATE) {
	MIN_SHIP_BY_DATE = mIN_SHIP_BY_DATE;
}
public String getMODIFYPROGID_CONTAINER_DETAILS() {
	return MODIFYPROGID_CONTAINER_DETAILS;
}
public void setMODIFYPROGID_CONTAINER_DETAILS(String mODIFYPROGID_CONTAINER_DETAILS) {
	MODIFYPROGID_CONTAINER_DETAILS = mODIFYPROGID_CONTAINER_DETAILS;
}
public String getMODIFYTPROGID_ORDER() {
	return MODIFYTPROGID_ORDER;
}
public void setMODIFYTPROGID_ORDER(String mODIFYTPROGID_ORDER) {
	MODIFYTPROGID_ORDER = mODIFYTPROGID_ORDER;
}
public String getMODIFYTPROGID_ORDER_LINE() {
	return MODIFYTPROGID_ORDER_LINE;
}
public void setMODIFYTPROGID_ORDER_LINE(String mODIFYTPROGID_ORDER_LINE) {
	MODIFYTPROGID_ORDER_LINE = mODIFYTPROGID_ORDER_LINE;
}
public String getMODIFYTPROGID_SHIPMENT() {
	return MODIFYTPROGID_SHIPMENT;
}
public void setMODIFYTPROGID_SHIPMENT(String mODIFYTPROGID_SHIPMENT) {
	MODIFYTPROGID_SHIPMENT = mODIFYTPROGID_SHIPMENT;
}
public String getMODIFYTPROGID_SHIPMENT_CONTAINER() {
	return MODIFYTPROGID_SHIPMENT_CONTAINER;
}
public void setMODIFYTPROGID_SHIPMENT_CONTAINER(String mODIFYTPROGID_SHIPMENT_CONTAINER) {
	MODIFYTPROGID_SHIPMENT_CONTAINER = mODIFYTPROGID_SHIPMENT_CONTAINER;
}
public String getMODIFYTPROGID_SHIPMENT_LINE() {
	return MODIFYTPROGID_SHIPMENT_LINE;
}
public void setMODIFYTPROGID_SHIPMENT_LINE(String mODIFYTPROGID_SHIPMENT_LINE) {
	MODIFYTPROGID_SHIPMENT_LINE = mODIFYTPROGID_SHIPMENT_LINE;
}
public String getMODIFYTS_CONTAINER_DETAILS() {
	return MODIFYTS_CONTAINER_DETAILS;
}
public void setMODIFYTS_CONTAINER_DETAILS(String mODIFYTS_CONTAINER_DETAILS) {
	MODIFYTS_CONTAINER_DETAILS = mODIFYTS_CONTAINER_DETAILS;
}
public String getMODIFYTS_ORDER() {
	return MODIFYTS_ORDER;
}
public void setMODIFYTS_ORDER(String mODIFYTS_ORDER) {
	MODIFYTS_ORDER = mODIFYTS_ORDER;
}
public String getMODIFYTS_ORDER_LINE() {
	return MODIFYTS_ORDER_LINE;
}
public void setMODIFYTS_ORDER_LINE(String mODIFYTS_ORDER_LINE) {
	MODIFYTS_ORDER_LINE = mODIFYTS_ORDER_LINE;
}
public String getMODIFYTS_SHIPMENT() {
	return MODIFYTS_SHIPMENT;
}
public void setMODIFYTS_SHIPMENT(String mODIFYTS_SHIPMENT) {
	MODIFYTS_SHIPMENT = mODIFYTS_SHIPMENT;
}
public String getMODIFYTS_SHIPMENT_CONTAINER() {
	return MODIFYTS_SHIPMENT_CONTAINER;
}
public void setMODIFYTS_SHIPMENT_CONTAINER(String mODIFYTS_SHIPMENT_CONTAINER) {
	MODIFYTS_SHIPMENT_CONTAINER = mODIFYTS_SHIPMENT_CONTAINER;
}
public String getMODIFYTS_SHIPMENT_LINE() {
	return MODIFYTS_SHIPMENT_LINE;
}
public void setMODIFYTS_SHIPMENT_LINE(String mODIFYTS_SHIPMENT_LINE) {
	MODIFYTS_SHIPMENT_LINE = mODIFYTS_SHIPMENT_LINE;
}
public String getMODIFYUSERID_CONTAINER_DETAILS() {
	return MODIFYUSERID_CONTAINER_DETAILS;
}
public void setMODIFYUSERID_CONTAINER_DETAILS(String mODIFYUSERID_CONTAINER_DETAILS) {
	MODIFYUSERID_CONTAINER_DETAILS = mODIFYUSERID_CONTAINER_DETAILS;
}
public String getMODIFYUSERID_ORDER() {
	return MODIFYUSERID_ORDER;
}
public void setMODIFYUSERID_ORDER(String mODIFYUSERID_ORDER) {
	MODIFYUSERID_ORDER = mODIFYUSERID_ORDER;
}
public String getMODIFYUSERID_ORDER_LINE() {
	return MODIFYUSERID_ORDER_LINE;
}
public void setMODIFYUSERID_ORDER_LINE(String mODIFYUSERID_ORDER_LINE) {
	MODIFYUSERID_ORDER_LINE = mODIFYUSERID_ORDER_LINE;
}
public String getMODIFYUSERID_SHIPMENT() {
	return MODIFYUSERID_SHIPMENT;
}
public void setMODIFYUSERID_SHIPMENT(String mODIFYUSERID_SHIPMENT) {
	MODIFYUSERID_SHIPMENT = mODIFYUSERID_SHIPMENT;
}
public String getMODIFYUSERID_SHIPMENT_CONTAINER() {
	return MODIFYUSERID_SHIPMENT_CONTAINER;
}
public void setMODIFYUSERID_SHIPMENT_CONTAINER(String mODIFYUSERID_SHIPMENT_CONTAINER) {
	MODIFYUSERID_SHIPMENT_CONTAINER = mODIFYUSERID_SHIPMENT_CONTAINER;
}
public String getMODIFYUSERID_SHIPMENT_LINE() {
	return MODIFYUSERID_SHIPMENT_LINE;
}
public void setMODIFYUSERID_SHIPMENT_LINE(String mODIFYUSERID_SHIPMENT_LINE) {
	MODIFYUSERID_SHIPMENT_LINE = mODIFYUSERID_SHIPMENT_LINE;
}
public String getNOTIFICATION_REFERENCE() {
	return NOTIFICATION_REFERENCE;
}
public void setNOTIFICATION_REFERENCE(String nOTIFICATION_REFERENCE) {
	NOTIFICATION_REFERENCE = nOTIFICATION_REFERENCE;
}
public String getNOTIFICATION_TYPE() {
	return NOTIFICATION_TYPE;
}
public void setNOTIFICATION_TYPE(String nOTIFICATION_TYPE) {
	NOTIFICATION_TYPE = nOTIFICATION_TYPE;
}
public String getOMS_CUSTOMER_ID() {
	return OMS_CUSTOMER_ID;
}
public void setOMS_CUSTOMER_ID(String oMS_CUSTOMER_ID) {
	OMS_CUSTOMER_ID = oMS_CUSTOMER_ID;
}
public String getORDERED_STORE_ID() {
	return ORDERED_STORE_ID;
}
public void setORDERED_STORE_ID(String oRDERED_STORE_ID) {
	ORDERED_STORE_ID = oRDERED_STORE_ID;
}
public String getORDERING_STORE() {
	return ORDERING_STORE;
}
public void setORDERING_STORE(String oRDERING_STORE) {
	ORDERING_STORE = oRDERING_STORE;
}
public String getORDER_CAPTURE_CHANNEL() {
	return ORDER_CAPTURE_CHANNEL;
}
public void setORDER_CAPTURE_CHANNEL(String oRDER_CAPTURE_CHANNEL) {
	ORDER_CAPTURE_CHANNEL = oRDER_CAPTURE_CHANNEL;
}
public String getORDER_CLOSED() {
	return ORDER_CLOSED;
}
public void setORDER_CLOSED(String oRDER_CLOSED) {
	ORDER_CLOSED = oRDER_CLOSED;
}
public String getORDER_CUSTOM_PO_NOS() {
	return ORDER_CUSTOM_PO_NOS;
}
public void setORDER_CUSTOM_PO_NOS(String oRDER_CUSTOM_PO_NOS) {
	ORDER_CUSTOM_PO_NOS = oRDER_CUSTOM_PO_NOS;
}
public String getORDER_DATE() {
	return ORDER_DATE;
}
public void setORDER_DATE(String oRDER_DATE) {
	ORDER_DATE = oRDER_DATE;
}
public String getORDER_EXPEDITE_FLAG() {
	return ORDER_EXPEDITE_FLAG;
}
public void setORDER_EXPEDITE_FLAG(String oRDER_EXPEDITE_FLAG) {
	ORDER_EXPEDITE_FLAG = oRDER_EXPEDITE_FLAG;
}
public String getORDER_FTC_EXEMPT() {
	return ORDER_FTC_EXEMPT;
}
public void setORDER_FTC_EXEMPT(String oRDER_FTC_EXEMPT) {
	ORDER_FTC_EXEMPT = oRDER_FTC_EXEMPT;
}
public String getORDER_HEADER_KEY() {
	return ORDER_HEADER_KEY;
}
public void setORDER_HEADER_KEY(String oRDER_HEADER_KEY) {
	ORDER_HEADER_KEY = oRDER_HEADER_KEY;
}
public String getORDER_HOLD_FLAG() {
	return ORDER_HOLD_FLAG;
}
public void setORDER_HOLD_FLAG(String oRDER_HOLD_FLAG) {
	ORDER_HOLD_FLAG = oRDER_HOLD_FLAG;
}
public String getORDER_INVOICE_COMPLETE() {
	return ORDER_INVOICE_COMPLETE;
}
public void setORDER_INVOICE_COMPLETE(String oRDER_INVOICE_COMPLETE) {
	ORDER_INVOICE_COMPLETE = oRDER_INVOICE_COMPLETE;
}
public long getORDER_LINE_INVOICED_QUANTITY() {
	return ORDER_LINE_INVOICED_QUANTITY;
}
public void setORDER_LINE_INVOICED_QUANTITY(long oRDER_LINE_INVOICED_QUANTITY) {
	ORDER_LINE_INVOICED_QUANTITY = oRDER_LINE_INVOICED_QUANTITY;
}
public String getORDER_LINE_KEY() {
	return ORDER_LINE_KEY;
}
public void setORDER_LINE_KEY(String oRDER_LINE_KEY) {
	ORDER_LINE_KEY = oRDER_LINE_KEY;
}
public long getORDER_LINE_ORDERED_QTY() {
	return ORDER_LINE_ORDERED_QTY;
}
public void setORDER_LINE_ORDERED_QTY(long oRDER_LINE_ORDERED_QTY) {
	ORDER_LINE_ORDERED_QTY = oRDER_LINE_ORDERED_QTY;
}
public String getORDER_LINE_TYPE() {
	return ORDER_LINE_TYPE;
}
public void setORDER_LINE_TYPE(String oRDER_LINE_TYPE) {
	ORDER_LINE_TYPE = oRDER_LINE_TYPE;
}
public String getORDER_LOS() {
	return ORDER_LOS;
}
public void setORDER_LOS(String oRDER_LOS) {
	ORDER_LOS = oRDER_LOS;
}
public String getORDER_NEXT_ALERT_TS() {
	return ORDER_NEXT_ALERT_TS;
}
public void setORDER_NEXT_ALERT_TS(String oRDER_NEXT_ALERT_TS) {
	ORDER_NEXT_ALERT_TS = oRDER_NEXT_ALERT_TS;
}
public String getORDER_NO() {
	return ORDER_NO;
}
public void setORDER_NO(String oRDER_NO) {
	ORDER_NO = oRDER_NO;
}
public long getORDER_ORIGINAL_TAX() {
	return ORDER_ORIGINAL_TAX;
}
public void setORDER_ORIGINAL_TAX(long oRDER_ORIGINAL_TAX) {
	ORDER_ORIGINAL_TAX = oRDER_ORIGINAL_TAX;
}
public double getORDER_ORIGINAL_TOTAL_AMOUNT() {
	return ORDER_ORIGINAL_TOTAL_AMOUNT;
}
public void setORDER_ORIGINAL_TOTAL_AMOUNT(double oRDER_ORIGINAL_TOTAL_AMOUNT) {
	ORDER_ORIGINAL_TOTAL_AMOUNT = oRDER_ORIGINAL_TOTAL_AMOUNT;
}
public long getORDER_OTHER_CHARGES() {
	return ORDER_OTHER_CHARGES;
}
public void setORDER_OTHER_CHARGES(long oRDER_OTHER_CHARGES) {
	ORDER_OTHER_CHARGES = oRDER_OTHER_CHARGES;
}
public String getORDER_PICKUP_STORE_ID() {
	return ORDER_PICKUP_STORE_ID;
}
public void setORDER_PICKUP_STORE_ID(String oRDER_PICKUP_STORE_ID) {
	ORDER_PICKUP_STORE_ID = oRDER_PICKUP_STORE_ID;
}
public String getORDER_PURPOSE() {
	return ORDER_PURPOSE;
}
public void setORDER_PURPOSE(String oRDER_PURPOSE) {
	ORDER_PURPOSE = oRDER_PURPOSE;
}
public String getORDER_QUOTE_EXP_DATE() {
	return ORDER_QUOTE_EXP_DATE;
}
public void setORDER_QUOTE_EXP_DATE(String oRDER_QUOTE_EXP_DATE) {
	ORDER_QUOTE_EXP_DATE = oRDER_QUOTE_EXP_DATE;
}
public String getORDER_RELEASE_KEY() {
	return ORDER_RELEASE_KEY;
}
public void setORDER_RELEASE_KEY(String oRDER_RELEASE_KEY) {
	ORDER_RELEASE_KEY = oRDER_RELEASE_KEY;
}
public String getORDER_REQ_CANCEL_DATE() {
	return ORDER_REQ_CANCEL_DATE;
}
public void setORDER_REQ_CANCEL_DATE(String oRDER_REQ_CANCEL_DATE) {
	ORDER_REQ_CANCEL_DATE = oRDER_REQ_CANCEL_DATE;
}
public String getORDER_REQ_DELIVERY_DATE() {
	return ORDER_REQ_DELIVERY_DATE;
}
public void setORDER_REQ_DELIVERY_DATE(String oRDER_REQ_DELIVERY_DATE) {
	ORDER_REQ_DELIVERY_DATE = oRDER_REQ_DELIVERY_DATE;
}
public String getORDER_REQ_SHIP_DATE() {
	return ORDER_REQ_SHIP_DATE;
}
public void setORDER_REQ_SHIP_DATE(String oRDER_REQ_SHIP_DATE) {
	ORDER_REQ_SHIP_DATE = oRDER_REQ_SHIP_DATE;
}
public long getORDER_TAX() {
	return ORDER_TAX;
}
public void setORDER_TAX(long oRDER_TAX) {
	ORDER_TAX = oRDER_TAX;
}
public String getORDER_TAX_EXEMPT_FLAG() {
	return ORDER_TAX_EXEMPT_FLAG;
}
public void setORDER_TAX_EXEMPT_FLAG(String oRDER_TAX_EXEMPT_FLAG) {
	ORDER_TAX_EXEMPT_FLAG = oRDER_TAX_EXEMPT_FLAG;
}
public double getORDER_TOTAL_AMOUNT() {
	return ORDER_TOTAL_AMOUNT;
}
public void setORDER_TOTAL_AMOUNT(double oRDER_TOTAL_AMOUNT) {
	ORDER_TOTAL_AMOUNT = oRDER_TOTAL_AMOUNT;
}
public String getORDER_TYPE() {
	return ORDER_TYPE;
}
public void setORDER_TYPE(String oRDER_TYPE) {
	ORDER_TYPE = oRDER_TYPE;
}
public long getOVERRIDED_PRICE() {
	return OVERRIDED_PRICE;
}
public void setOVERRIDED_PRICE(long oVERRIDED_PRICE) {
	OVERRIDED_PRICE = oVERRIDED_PRICE;
}
public String getPARENT_SHIPMENT_LINE_KEY() {
	return PARENT_SHIPMENT_LINE_KEY;
}
public void setPARENT_SHIPMENT_LINE_KEY(String pARENT_SHIPMENT_LINE_KEY) {
	PARENT_SHIPMENT_LINE_KEY = pARENT_SHIPMENT_LINE_KEY;
}
public String getPAYMENT_RULE_ID() {
	return PAYMENT_RULE_ID;
}
public void setPAYMENT_RULE_ID(String pAYMENT_RULE_ID) {
	PAYMENT_RULE_ID = pAYMENT_RULE_ID;
}
public String getPAYMENT_STATUS() {
	return PAYMENT_STATUS;
}
public void setPAYMENT_STATUS(String pAYMENT_STATUS) {
	PAYMENT_STATUS = pAYMENT_STATUS;
}
public String getPICKED_UP_BY() {
	return PICKED_UP_BY;
}
public void setPICKED_UP_BY(String pICKED_UP_BY) {
	PICKED_UP_BY = pICKED_UP_BY;
}
public long getPICKED_UP_BY_CUSTOMER_QTY() {
	return PICKED_UP_BY_CUSTOMER_QTY;
}
public void setPICKED_UP_BY_CUSTOMER_QTY(long pICKED_UP_BY_CUSTOMER_QTY) {
	PICKED_UP_BY_CUSTOMER_QTY = pICKED_UP_BY_CUSTOMER_QTY;
}
public String getPICKED_UP_DATE() {
	return PICKED_UP_DATE;
}
public void setPICKED_UP_DATE(String pICKED_UP_DATE) {
	PICKED_UP_DATE = pICKED_UP_DATE;
}
public String getPICKED_UP_ID_EXPIRY_DATE() {
	return PICKED_UP_ID_EXPIRY_DATE;
}
public void setPICKED_UP_ID_EXPIRY_DATE(String pICKED_UP_ID_EXPIRY_DATE) {
	PICKED_UP_ID_EXPIRY_DATE = pICKED_UP_ID_EXPIRY_DATE;
}
public String getPICKED_UP_ID_TYPE_STATE_ISSUED() {
	return PICKED_UP_ID_TYPE_STATE_ISSUED;
}
public void setPICKED_UP_ID_TYPE_STATE_ISSUED(String pICKED_UP_ID_TYPE_STATE_ISSUED) {
	PICKED_UP_ID_TYPE_STATE_ISSUED = pICKED_UP_ID_TYPE_STATE_ISSUED;
}
public String getPICKED_UP_VERIFICATION_ID() {
	return PICKED_UP_VERIFICATION_ID;
}
public void setPICKED_UP_VERIFICATION_ID(String pICKED_UP_VERIFICATION_ID) {
	PICKED_UP_VERIFICATION_ID = pICKED_UP_VERIFICATION_ID;
}
public String getPICKED_UP_VERIFIED() {
	return PICKED_UP_VERIFIED;
}
public void setPICKED_UP_VERIFIED(String pICKED_UP_VERIFIED) {
	PICKED_UP_VERIFIED = pICKED_UP_VERIFIED;
}
public String getPOS_RETURN_11_TICKET_NO() {
	return POS_RETURN_11_TICKET_NO;
}
public void setPOS_RETURN_11_TICKET_NO(String pOS_RETURN_11_TICKET_NO) {
	POS_RETURN_11_TICKET_NO = pOS_RETURN_11_TICKET_NO;
}
public String getPRICE_OVERRIDE_EMP_ID() {
	return PRICE_OVERRIDE_EMP_ID;
}
public void setPRICE_OVERRIDE_EMP_ID(String pRICE_OVERRIDE_EMP_ID) {
	PRICE_OVERRIDE_EMP_ID = pRICE_OVERRIDE_EMP_ID;
}
public String getPRIORITY_CODE() {
	return PRIORITY_CODE;
}
public void setPRIORITY_CODE(String pRIORITY_CODE) {
	PRIORITY_CODE = pRIORITY_CODE;
}
public String getPROBLEM_WITH_CARTON() {
	return PROBLEM_WITH_CARTON;
}
public void setPROBLEM_WITH_CARTON(String pROBLEM_WITH_CARTON) {
	PROBLEM_WITH_CARTON = pROBLEM_WITH_CARTON;
}
public String getPRODUCT_CLASS() {
	return PRODUCT_CLASS;
}
public void setPRODUCT_CLASS(String pRODUCT_CLASS) {
	PRODUCT_CLASS = pRODUCT_CLASS;
}
public String getPRODUCT_LINE() {
	return PRODUCT_LINE;
}
public void setPRODUCT_LINE(String pRODUCT_LINE) {
	PRODUCT_LINE = pRODUCT_LINE;
}
public long getQUANTITY_IN_CONTAINER() {
	return QUANTITY_IN_CONTAINER;
}
public void setQUANTITY_IN_CONTAINER(long qUANTITY_IN_CONTAINER) {
	QUANTITY_IN_CONTAINER = qUANTITY_IN_CONTAINER;
}
public String getQUOTE_LINE_SENT_FLAG() {
	return QUOTE_LINE_SENT_FLAG;
}
public void setQUOTE_LINE_SENT_FLAG(String qUOTE_LINE_SENT_FLAG) {
	QUOTE_LINE_SENT_FLAG = qUOTE_LINE_SENT_FLAG;
}
public String getQUOTE_MAX_QUANTITY() {
	return QUOTE_MAX_QUANTITY;
}
public void setQUOTE_MAX_QUANTITY(String qUOTE_MAX_QUANTITY) {
	QUOTE_MAX_QUANTITY = qUOTE_MAX_QUANTITY;
}
public String getQUOTE_MIN_QUANTITY() {
	return QUOTE_MIN_QUANTITY;
}
public void setQUOTE_MIN_QUANTITY(String qUOTE_MIN_QUANTITY) {
	QUOTE_MIN_QUANTITY = qUOTE_MIN_QUANTITY;
}
public String getQUOTE_ORDER_SENT() {
	return QUOTE_ORDER_SENT;
}
public void setQUOTE_ORDER_SENT(String qUOTE_ORDER_SENT) {
	QUOTE_ORDER_SENT = qUOTE_ORDER_SENT;
}
public String getREFUND_ON_ACCOUNT_FLAG() {
	return REFUND_ON_ACCOUNT_FLAG;
}
public void setREFUND_ON_ACCOUNT_FLAG(String rEFUND_ON_ACCOUNT_FLAG) {
	REFUND_ON_ACCOUNT_FLAG = rEFUND_ON_ACCOUNT_FLAG;
}
public String getREFUND_TO_ACCOUNT_FLAG() {
	return REFUND_TO_ACCOUNT_FLAG;
}
public void setREFUND_TO_ACCOUNT_FLAG(String rEFUND_TO_ACCOUNT_FLAG) {
	REFUND_TO_ACCOUNT_FLAG = rEFUND_TO_ACCOUNT_FLAG;
}
public String getREQUESTED_DELIVERY_DATE() {
	return REQUESTED_DELIVERY_DATE;
}
public void setREQUESTED_DELIVERY_DATE(String rEQUESTED_DELIVERY_DATE) {
	REQUESTED_DELIVERY_DATE = rEQUESTED_DELIVERY_DATE;
}
public String getREQUESTED_SHIPMENT_DATE() {
	return REQUESTED_SHIPMENT_DATE;
}
public void setREQUESTED_SHIPMENT_DATE(String rEQUESTED_SHIPMENT_DATE) {
	REQUESTED_SHIPMENT_DATE = rEQUESTED_SHIPMENT_DATE;
}
public String getRESHIP_PARENT_LINE_KEY() {
	return RESHIP_PARENT_LINE_KEY;
}
public void setRESHIP_PARENT_LINE_KEY(String rESHIP_PARENT_LINE_KEY) {
	RESHIP_PARENT_LINE_KEY = rESHIP_PARENT_LINE_KEY;
}
public String getRESTRICT_SHIP_FROM_STORE() {
	return RESTRICT_SHIP_FROM_STORE;
}
public void setRESTRICT_SHIP_FROM_STORE(String rESTRICT_SHIP_FROM_STORE) {
	RESTRICT_SHIP_FROM_STORE = rESTRICT_SHIP_FROM_STORE;
}
public String getRETURN_BY_GIFT_RECIPIENT() {
	return RETURN_BY_GIFT_RECIPIENT;
}
public void setRETURN_BY_GIFT_RECIPIENT(String rETURN_BY_GIFT_RECIPIENT) {
	RETURN_BY_GIFT_RECIPIENT = rETURN_BY_GIFT_RECIPIENT;
}
public String getRETURN_OH_KEY_FOR_EXCHANGE() {
	return RETURN_OH_KEY_FOR_EXCHANGE;
}
public void setRETURN_OH_KEY_FOR_EXCHANGE(String rETURN_OH_KEY_FOR_EXCHANGE) {
	RETURN_OH_KEY_FOR_EXCHANGE = rETURN_OH_KEY_FOR_EXCHANGE;
}
public String getRETURN_REASON() {
	return RETURN_REASON;
}
public void setRETURN_REASON(String rETURN_REASON) {
	RETURN_REASON = rETURN_REASON;
}
public String getRETURN_REC_DUMMY_AMOUNT() {
	return RETURN_REC_DUMMY_AMOUNT;
}
public void setRETURN_REC_DUMMY_AMOUNT(String rETURN_REC_DUMMY_AMOUNT) {
	RETURN_REC_DUMMY_AMOUNT = rETURN_REC_DUMMY_AMOUNT;
}
public String getRETURN_RIS_NO() {
	return RETURN_RIS_NO;
}
public void setRETURN_RIS_NO(String rETURN_RIS_NO) {
	RETURN_RIS_NO = rETURN_RIS_NO;
}
public String getRETURN_VPO_NO() {
	return RETURN_VPO_NO;
}
public void setRETURN_VPO_NO(String rETURN_VPO_NO) {
	RETURN_VPO_NO = rETURN_VPO_NO;
}
public String getSEGMENT() {
	return SEGMENT;
}
public void setSEGMENT(String sEGMENT) {
	SEGMENT = sEGMENT;
}
public String getSEGMENT_TYPE() {
	return SEGMENT_TYPE;
}
public void setSEGMENT_TYPE(String sEGMENT_TYPE) {
	SEGMENT_TYPE = sEGMENT_TYPE;
}
public String getSELLER_ORGANIZATION_CODE() {
	return SELLER_ORGANIZATION_CODE;
}
public void setSELLER_ORGANIZATION_CODE(String sELLER_ORGANIZATION_CODE) {
	SELLER_ORGANIZATION_CODE = sELLER_ORGANIZATION_CODE;
}
public String getSENT_FOR_FRAUD_CHECK() {
	return SENT_FOR_FRAUD_CHECK;
}
public void setSENT_FOR_FRAUD_CHECK(String sENT_FOR_FRAUD_CHECK) {
	SENT_FOR_FRAUD_CHECK = sENT_FOR_FRAUD_CHECK;
}
public String getSHIPMENT_CARRIER_CODE() {
	return SHIPMENT_CARRIER_CODE;
}
public void setSHIPMENT_CARRIER_CODE(String sHIPMENT_CARRIER_CODE) {
	SHIPMENT_CARRIER_CODE = sHIPMENT_CARRIER_CODE;
}
public String getSHIPMENT_CLOSED_FLAG() {
	return SHIPMENT_CLOSED_FLAG;
}
public void setSHIPMENT_CLOSED_FLAG(String sHIPMENT_CLOSED_FLAG) {
	SHIPMENT_CLOSED_FLAG = sHIPMENT_CLOSED_FLAG;
}
public String getSHIPMENT_CONTAINERIZED_FLAG() {
	return SHIPMENT_CONTAINERIZED_FLAG;
}
public void setSHIPMENT_CONTAINERIZED_FLAG(String sHIPMENT_CONTAINERIZED_FLAG) {
	SHIPMENT_CONTAINERIZED_FLAG = sHIPMENT_CONTAINERIZED_FLAG;
}
public long getSHIPMENT_CONTAINERIZED_QUANTITY() {
	return SHIPMENT_CONTAINERIZED_QUANTITY;
}
public void setSHIPMENT_CONTAINERIZED_QUANTITY(long sHIPMENT_CONTAINERIZED_QUANTITY) {
	SHIPMENT_CONTAINERIZED_QUANTITY = sHIPMENT_CONTAINERIZED_QUANTITY;
}
public String getSHIPMENT_CONTAINER_KEY() {
	return SHIPMENT_CONTAINER_KEY;
}
public void setSHIPMENT_CONTAINER_KEY(String sHIPMENT_CONTAINER_KEY) {
	SHIPMENT_CONTAINER_KEY = sHIPMENT_CONTAINER_KEY;
}
public String getSHIPMENT_CUSTOM_PACK_STATUS_DATE() {
	return SHIPMENT_CUSTOM_PACK_STATUS_DATE;
}
public void setSHIPMENT_CUSTOM_PACK_STATUS_DATE(String sHIPMENT_CUSTOM_PACK_STATUS_DATE) {
	SHIPMENT_CUSTOM_PACK_STATUS_DATE = sHIPMENT_CUSTOM_PACK_STATUS_DATE;
}
public String getSHIPMENT_CUSTOM_SHIP_DATE() {
	return SHIPMENT_CUSTOM_SHIP_DATE;
}
public void setSHIPMENT_CUSTOM_SHIP_DATE(String sHIPMENT_CUSTOM_SHIP_DATE) {
	SHIPMENT_CUSTOM_SHIP_DATE = sHIPMENT_CUSTOM_SHIP_DATE;
}
public String getSHIPMENT_DELIVERY_METHOD() {
	return SHIPMENT_DELIVERY_METHOD;
}
public void setSHIPMENT_DELIVERY_METHOD(String sHIPMENT_DELIVERY_METHOD) {
	SHIPMENT_DELIVERY_METHOD = sHIPMENT_DELIVERY_METHOD;
}
public double getSHIPMENT_FREIGHT_CHARGE() {
	return SHIPMENT_FREIGHT_CHARGE;
}
public void setSHIPMENT_FREIGHT_CHARGE(double sHIPMENT_FREIGHT_CHARGE) {
	SHIPMENT_FREIGHT_CHARGE = sHIPMENT_FREIGHT_CHARGE;
}
public String getSHIPMENT_FULFILLMENT_TYPE() {
	return SHIPMENT_FULFILLMENT_TYPE;
}
public void setSHIPMENT_FULFILLMENT_TYPE(String sHIPMENT_FULFILLMENT_TYPE) {
	SHIPMENT_FULFILLMENT_TYPE = sHIPMENT_FULFILLMENT_TYPE;
}
public String getSHIPMENT_INVOICE_COMPLETE() {
	return SHIPMENT_INVOICE_COMPLETE;
}
public void setSHIPMENT_INVOICE_COMPLETE(String sHIPMENT_INVOICE_COMPLETE) {
	SHIPMENT_INVOICE_COMPLETE = sHIPMENT_INVOICE_COMPLETE;
}
public String getSHIPMENT_KEY() {
	return SHIPMENT_KEY;
}
public void setSHIPMENT_KEY(String sHIPMENT_KEY) {
	SHIPMENT_KEY = sHIPMENT_KEY;
}
public String getSHIPMENT_LINE_ACTUAL_SERIAL_NUMBER() {
	return SHIPMENT_LINE_ACTUAL_SERIAL_NUMBER;
}
public void setSHIPMENT_LINE_ACTUAL_SERIAL_NUMBER(String sHIPMENT_LINE_ACTUAL_SERIAL_NUMBER) {
	SHIPMENT_LINE_ACTUAL_SERIAL_NUMBER = sHIPMENT_LINE_ACTUAL_SERIAL_NUMBER;
}
public long getSHIPMENT_LINE_BACKROOM_PICKED_QTY() {
	return SHIPMENT_LINE_BACKROOM_PICKED_QTY;
}
public void setSHIPMENT_LINE_BACKROOM_PICKED_QTY(long sHIPMENT_LINE_BACKROOM_PICKED_QTY) {
	SHIPMENT_LINE_BACKROOM_PICKED_QTY = sHIPMENT_LINE_BACKROOM_PICKED_QTY;
}
public String getSHIPMENT_LINE_BACKROOM_PICK_COMPLETE() {
	return SHIPMENT_LINE_BACKROOM_PICK_COMPLETE;
}
public void setSHIPMENT_LINE_BACKROOM_PICK_COMPLETE(String sHIPMENT_LINE_BACKROOM_PICK_COMPLETE) {
	SHIPMENT_LINE_BACKROOM_PICK_COMPLETE = sHIPMENT_LINE_BACKROOM_PICK_COMPLETE;
}
public String getSHIPMENT_LINE_DESC() {
	return SHIPMENT_LINE_DESC;
}
public void setSHIPMENT_LINE_DESC(String sHIPMENT_LINE_DESC) {
	SHIPMENT_LINE_DESC = sHIPMENT_LINE_DESC;
}
public String getSHIPMENT_LINE_KEY() {
	return SHIPMENT_LINE_KEY;
}
public void setSHIPMENT_LINE_KEY(String sHIPMENT_LINE_KEY) {
	SHIPMENT_LINE_KEY = sHIPMENT_LINE_KEY;
}
public long getSHIPMENT_LINE_KIT_QTY() {
	return SHIPMENT_LINE_KIT_QTY;
}
public void setSHIPMENT_LINE_KIT_QTY(long sHIPMENT_LINE_KIT_QTY) {
	SHIPMENT_LINE_KIT_QTY = sHIPMENT_LINE_KIT_QTY;
}
public long getSHIPMENT_LINE_NO() {
	return SHIPMENT_LINE_NO;
}
public void setSHIPMENT_LINE_NO(long sHIPMENT_LINE_NO) {
	SHIPMENT_LINE_NO = sHIPMENT_LINE_NO;
}
public long getSHIPMENT_LINE_ORIGINAL_QTY() {
	return SHIPMENT_LINE_ORIGINAL_QTY;
}
public void setSHIPMENT_LINE_ORIGINAL_QTY(long sHIPMENT_LINE_ORIGINAL_QTY) {
	SHIPMENT_LINE_ORIGINAL_QTY = sHIPMENT_LINE_ORIGINAL_QTY;
}
public long getSHIPMENT_LINE_OVER_SHIP_QTY() {
	return SHIPMENT_LINE_OVER_SHIP_QTY;
}
public void setSHIPMENT_LINE_OVER_SHIP_QTY(long sHIPMENT_LINE_OVER_SHIP_QTY) {
	SHIPMENT_LINE_OVER_SHIP_QTY = sHIPMENT_LINE_OVER_SHIP_QTY;
}
public String getSHIPMENT_LINE_POS_RESERVATION_ID() {
	return SHIPMENT_LINE_POS_RESERVATION_ID;
}
public void setSHIPMENT_LINE_POS_RESERVATION_ID(String sHIPMENT_LINE_POS_RESERVATION_ID) {
	SHIPMENT_LINE_POS_RESERVATION_ID = sHIPMENT_LINE_POS_RESERVATION_ID;
}
public String getSHIPMENT_LINE_POS_SKU_NUMBER() {
	return SHIPMENT_LINE_POS_SKU_NUMBER;
}
public void setSHIPMENT_LINE_POS_SKU_NUMBER(String sHIPMENT_LINE_POS_SKU_NUMBER) {
	SHIPMENT_LINE_POS_SKU_NUMBER = sHIPMENT_LINE_POS_SKU_NUMBER;
}
public long getSHIPMENT_LINE_PRIME_LINE_NO() {
	return SHIPMENT_LINE_PRIME_LINE_NO;
}
public void setSHIPMENT_LINE_PRIME_LINE_NO(long sHIPMENT_LINE_PRIME_LINE_NO) {
	SHIPMENT_LINE_PRIME_LINE_NO = sHIPMENT_LINE_PRIME_LINE_NO;
}
public long getSHIPMENT_LINE_QUANTITY() {
	return SHIPMENT_LINE_QUANTITY;
}
public void setSHIPMENT_LINE_QUANTITY(long sHIPMENT_LINE_QUANTITY) {
	SHIPMENT_LINE_QUANTITY = sHIPMENT_LINE_QUANTITY;
}
public long getSHIPMENT_LINE_RELEASE_NO() {
	return SHIPMENT_LINE_RELEASE_NO;
}
public void setSHIPMENT_LINE_RELEASE_NO(long sHIPMENT_LINE_RELEASE_NO) {
	SHIPMENT_LINE_RELEASE_NO = sHIPMENT_LINE_RELEASE_NO;
}
public String getSHIPMENT_LINE_SERIALIZED_ITEM_FLAG() {
	return SHIPMENT_LINE_SERIALIZED_ITEM_FLAG;
}
public void setSHIPMENT_LINE_SERIALIZED_ITEM_FLAG(String sHIPMENT_LINE_SERIALIZED_ITEM_FLAG) {
	SHIPMENT_LINE_SERIALIZED_ITEM_FLAG = sHIPMENT_LINE_SERIALIZED_ITEM_FLAG;
}
public long getSHIPMENT_LINE_SUB_LINE_NO() {
	return SHIPMENT_LINE_SUB_LINE_NO;
}
public void setSHIPMENT_LINE_SUB_LINE_NO(long sHIPMENT_LINE_SUB_LINE_NO) {
	SHIPMENT_LINE_SUB_LINE_NO = sHIPMENT_LINE_SUB_LINE_NO;
}
public String getSHIPMENT_LINE_USED_VINTAGE_ITEM_FLAG() {
	return SHIPMENT_LINE_USED_VINTAGE_ITEM_FLAG;
}
public void setSHIPMENT_LINE_USED_VINTAGE_ITEM_FLAG(String sHIPMENT_LINE_USED_VINTAGE_ITEM_FLAG) {
	SHIPMENT_LINE_USED_VINTAGE_ITEM_FLAG = sHIPMENT_LINE_USED_VINTAGE_ITEM_FLAG;
}
public String getSHIPMENT_LOS() {
	return SHIPMENT_LOS;
}
public void setSHIPMENT_LOS(String sHIPMENT_LOS) {
	SHIPMENT_LOS = sHIPMENT_LOS;
}
public String getSHIPMENT_MUST_SHIP_BEFORE() {
	return SHIPMENT_MUST_SHIP_BEFORE;
}
public void setSHIPMENT_MUST_SHIP_BEFORE(String sHIPMENT_MUST_SHIP_BEFORE) {
	SHIPMENT_MUST_SHIP_BEFORE = sHIPMENT_MUST_SHIP_BEFORE;
}
public String getSHIPMENT_NO() {
	return SHIPMENT_NO;
}
public void setSHIPMENT_NO(String sHIPMENT_NO) {
	SHIPMENT_NO = sHIPMENT_NO;
}
public String getSHIPMENT_PACKLIST_TYPE() {
	return SHIPMENT_PACKLIST_TYPE;
}
public void setSHIPMENT_PACKLIST_TYPE(String sHIPMENT_PACKLIST_TYPE) {
	SHIPMENT_PACKLIST_TYPE = sHIPMENT_PACKLIST_TYPE;
}
public String getSHIPMENT_PENDING_RECEIPT_DATE() {
	return SHIPMENT_PENDING_RECEIPT_DATE;
}
public void setSHIPMENT_PENDING_RECEIPT_DATE(String sHIPMENT_PENDING_RECEIPT_DATE) {
	SHIPMENT_PENDING_RECEIPT_DATE = sHIPMENT_PENDING_RECEIPT_DATE;
}
public String getSHIPMENT_PICKREQUEST_NO() {
	return SHIPMENT_PICKREQUEST_NO;
}
public void setSHIPMENT_PICKREQUEST_NO(String sHIPMENT_PICKREQUEST_NO) {
	SHIPMENT_PICKREQUEST_NO = sHIPMENT_PICKREQUEST_NO;
}
public String getSHIPMENT_PICKUP_STORE_ID() {
	return SHIPMENT_PICKUP_STORE_ID;
}
public void setSHIPMENT_PICKUP_STORE_ID(String sHIPMENT_PICKUP_STORE_ID) {
	SHIPMENT_PICKUP_STORE_ID = sHIPMENT_PICKUP_STORE_ID;
}
public String getSHIPMENT_PIPELINE_KEY() {
	return SHIPMENT_PIPELINE_KEY;
}
public void setSHIPMENT_PIPELINE_KEY(String sHIPMENT_PIPELINE_KEY) {
	SHIPMENT_PIPELINE_KEY = sHIPMENT_PIPELINE_KEY;
}
public long getSHIPMENT_PLACED_QUANTITY() {
	return SHIPMENT_PLACED_QUANTITY;
}
public void setSHIPMENT_PLACED_QUANTITY(long sHIPMENT_PLACED_QUANTITY) {
	SHIPMENT_PLACED_QUANTITY = sHIPMENT_PLACED_QUANTITY;
}
public String getSHIPMENT_POS_SALES_TICKET_NO() {
	return SHIPMENT_POS_SALES_TICKET_NO;
}
public void setSHIPMENT_POS_SALES_TICKET_NO(String sHIPMENT_POS_SALES_TICKET_NO) {
	SHIPMENT_POS_SALES_TICKET_NO = sHIPMENT_POS_SALES_TICKET_NO;
}
public String getSHIPMENT_RECEIVING_NODE() {
	return SHIPMENT_RECEIVING_NODE;
}
public void setSHIPMENT_RECEIVING_NODE(String sHIPMENT_RECEIVING_NODE) {
	SHIPMENT_RECEIVING_NODE = sHIPMENT_RECEIVING_NODE;
}
public String getSHIPMENT_REQUESTED_CARRIER_CODE() {
	return SHIPMENT_REQUESTED_CARRIER_CODE;
}
public void setSHIPMENT_REQUESTED_CARRIER_CODE(String sHIPMENT_REQUESTED_CARRIER_CODE) {
	SHIPMENT_REQUESTED_CARRIER_CODE = sHIPMENT_REQUESTED_CARRIER_CODE;
}
public String getSHIPMENT_SHIPNODE_KEY() {
	return SHIPMENT_SHIPNODE_KEY;
}
public void setSHIPMENT_SHIPNODE_KEY(String sHIPMENT_SHIPNODE_KEY) {
	SHIPMENT_SHIPNODE_KEY = sHIPMENT_SHIPNODE_KEY;
}
public String getSHIPMENT_SHIP_DATE() {
	return SHIPMENT_SHIP_DATE;
}
public void setSHIPMENT_SHIP_DATE(String sHIPMENT_SHIP_DATE) {
	SHIPMENT_SHIP_DATE = sHIPMENT_SHIP_DATE;
}
public String getSHIPMENT_STATUS() {
	return SHIPMENT_STATUS;
}
public void setSHIPMENT_STATUS(String sHIPMENT_STATUS) {
	SHIPMENT_STATUS = sHIPMENT_STATUS;
}
public String getSHIPMENT_STATUS_DATE() {
	return SHIPMENT_STATUS_DATE;
}
public void setSHIPMENT_STATUS_DATE(String sHIPMENT_STATUS_DATE) {
	SHIPMENT_STATUS_DATE = sHIPMENT_STATUS_DATE;
}
public String getSHIPMENT_STATUS_NAME() {
	return SHIPMENT_STATUS_NAME;
}
public void setSHIPMENT_STATUS_NAME(String sHIPMENT_STATUS_NAME) {
	SHIPMENT_STATUS_NAME = sHIPMENT_STATUS_NAME;
}
public long getSHIPMENT_TOTAL_QUANTITY() {
	return SHIPMENT_TOTAL_QUANTITY;
}
public void setSHIPMENT_TOTAL_QUANTITY(long sHIPMENT_TOTAL_QUANTITY) {
	SHIPMENT_TOTAL_QUANTITY = sHIPMENT_TOTAL_QUANTITY;
}
public String getSHIPMENT_TYPE() {
	return SHIPMENT_TYPE;
}
public void setSHIPMENT_TYPE(String sHIPMENT_TYPE) {
	SHIPMENT_TYPE = sHIPMENT_TYPE;
}
public long getSHIPMENT_UNPLACED_QUANTITY() {
	return SHIPMENT_UNPLACED_QUANTITY;
}
public void setSHIPMENT_UNPLACED_QUANTITY(long sHIPMENT_UNPLACED_QUANTITY) {
	SHIPMENT_UNPLACED_QUANTITY = sHIPMENT_UNPLACED_QUANTITY;
}
public double getSHIPMENT_VOLUME() {
	return SHIPMENT_VOLUME;
}
public void setSHIPMENT_VOLUME(double sHIPMENT_VOLUME) {
	SHIPMENT_VOLUME = sHIPMENT_VOLUME;
}
public String getSHIPMENT_VOLUME_UOM() {
	return SHIPMENT_VOLUME_UOM;
}
public void setSHIPMENT_VOLUME_UOM(String sHIPMENT_VOLUME_UOM) {
	SHIPMENT_VOLUME_UOM = sHIPMENT_VOLUME_UOM;
}
public double getSHIPMENT_WEIGHT() {
	return SHIPMENT_WEIGHT;
}
public void setSHIPMENT_WEIGHT(double sHIPMENT_WEIGHT) {
	SHIPMENT_WEIGHT = sHIPMENT_WEIGHT;
}
public String getSHIPMENT_WEIGHT_UOM() {
	return SHIPMENT_WEIGHT_UOM;
}
public void setSHIPMENT_WEIGHT_UOM(String sHIPMENT_WEIGHT_UOM) {
	SHIPMENT_WEIGHT_UOM = sHIPMENT_WEIGHT_UOM;
}
public String getSHIP_FROM_ADDRESS_LINE1() {
	return SHIP_FROM_ADDRESS_LINE1;
}
public void setSHIP_FROM_ADDRESS_LINE1(String sHIP_FROM_ADDRESS_LINE1) {
	SHIP_FROM_ADDRESS_LINE1 = sHIP_FROM_ADDRESS_LINE1;
}
public String getSHIP_FROM_COMPANY() {
	return SHIP_FROM_COMPANY;
}
public void setSHIP_FROM_COMPANY(String sHIP_FROM_COMPANY) {
	SHIP_FROM_COMPANY = sHIP_FROM_COMPANY;
}
public String getSHIP_TO_COMPANY() {
	return SHIP_TO_COMPANY;
}
public void setSHIP_TO_COMPANY(String sHIP_TO_COMPANY) {
	SHIP_TO_COMPANY = sHIP_TO_COMPANY;
}
public String getSHIP_TO_STORE_ID() {
	return SHIP_TO_STORE_ID;
}
public void setSHIP_TO_STORE_ID(String sHIP_TO_STORE_ID) {
	SHIP_TO_STORE_ID = sHIP_TO_STORE_ID;
}
public String getSOURCING_CLASSIFICATION() {
	return SOURCING_CLASSIFICATION;
}
public void setSOURCING_CLASSIFICATION(String sOURCING_CLASSIFICATION) {
	SOURCING_CLASSIFICATION = sOURCING_CLASSIFICATION;
}
public String getSTORE_CREDIT_FLAG() {
	return STORE_CREDIT_FLAG;
}
public void setSTORE_CREDIT_FLAG(String sTORE_CREDIT_FLAG) {
	STORE_CREDIT_FLAG = sTORE_CREDIT_FLAG;
}
public String getTAX_PRODUCT_CODE() {
	return TAX_PRODUCT_CODE;
}
public void setTAX_PRODUCT_CODE(String tAX_PRODUCT_CODE) {
	TAX_PRODUCT_CODE = tAX_PRODUCT_CODE;
}
public long getTOTAL_ADJUSTMENT_AMOUNT() {
	return TOTAL_ADJUSTMENT_AMOUNT;
}
public void setTOTAL_ADJUSTMENT_AMOUNT(long tOTAL_ADJUSTMENT_AMOUNT) {
	TOTAL_ADJUSTMENT_AMOUNT = tOTAL_ADJUSTMENT_AMOUNT;
}
public String getTO_CITY() {
	return TO_CITY;
}
public void setTO_CITY(String tO_CITY) {
	TO_CITY = tO_CITY;
}
public String getTO_STATE() {
	return TO_STATE;
}
public void setTO_STATE(String tO_STATE) {
	TO_STATE = tO_STATE;
}
public String getTRACKING_NO() {
	return TRACKING_NO;
}
public void setTRACKING_NO(String tRACKING_NO) {
	TRACKING_NO = tRACKING_NO;
}
public long getUNIT_COST() {
	return UNIT_COST;
}
public void setUNIT_COST(long uNIT_COST) {
	UNIT_COST = uNIT_COST;
}
public double getUNIT_PRICE() {
	return UNIT_PRICE;
}
public void setUNIT_PRICE(double uNIT_PRICE) {
	UNIT_PRICE = uNIT_PRICE;
}
public String getUOM() {
	return UOM;
}
public void setUOM(String uOM) {
	UOM = uOM;
}

public ContainerDetails() {
	
}
}
